//! Exercises the generated open.mp wrappers against a running server.
//!
//! Every wrapper under `samp::omp` is generated from the SDK headers, and every
//! slot the official binaries let us check is checked by
//! `scripts/check-abi-slots.py --generated`. What that cannot see is whether a
//! call works: the argument types, the return convention, the stack the callee
//! cleans. This plugin creates one entity of each kind the server offers, reads
//! back what it created, and round-trips every setter that has a matching getter
//! (`round_trips.rs`, generated by `scripts/omp-roundtrip.py`).
//!
//! An NPC stands in for a player, so the player-side wrappers run against a real
//! `IPlayer`. The server needs `max_bots` above zero in `config.json` for it.
//!
//! Load it as a component on open.mp, on Linux and on Windows. The summary line
//! should read `0 wrong` on both, with the same counts.

use log::info;
use samp::omp::{Component, StringView, Vector2, Vector3};
use samp::plugin::omp_query;
use samp::prelude::*;
use samp::{initialize_plugin, omp};

mod report;
// Generated for every handle with a set/get pair. Two have no way in yet — a
// player text label is created by an overloaded `create`, left to hand-written
// code, and the custom-models data has no generated accessor — so their round
// trips exist unused.
#[allow(clippy::all, clippy::pedantic, dead_code)]
mod round_trips;

use report::Report;

/// When the per-NPC checks run, counted from the first tick. The NPC connects
/// through its own network after `on_omp_ready`; its first driver sync sets the
/// vehicle's `driver`; components attach their per-player data on connect.
const DRIVER_SYNCED: std::time::Duration = std::time::Duration::from_secs(1);
const PLAYER_SYNCED: std::time::Duration = std::time::Duration::from_secs(3);

/// The NPC and what it was left with for the timed checks.
struct Npc {
    component: *mut omp::INPCComponent,
    npc: *mut omp::INPC,
    vehicle: *mut omp::IVehicle,
}

struct Showcase {
    report: Report,
    npc: Option<Npc>,
    started: Option<std::time::Instant>,
    driven: bool,
    finished: bool,
}

impl SampPlugin for Showcase {
    fn on_omp_ready(&mut self) {
        self.npc = unsafe { exercise(&mut self.report) };
        if self.npc.is_none() {
            self.finish();
        }
    }

    fn on_tick(&mut self, _ctx: samp::plugin::TickContext) {
        if self.finished {
            return;
        }
        let elapsed = self
            .started
            .get_or_insert_with(std::time::Instant::now)
            .elapsed();
        let Some(npc) = self.npc.as_ref() else {
            return;
        };

        if !self.driven && elapsed >= DRIVER_SYNCED {
            self.driven = true;
            unsafe { with_driver(npc, &mut self.report) };
        }
        if elapsed < PLAYER_SYNCED {
            return;
        }

        let npc = self.npc.take().expect("checked above");
        let player = unsafe { omp::npc_player(npc.npc) };
        if !player.is_null() {
            let at = Vector3 {
                x: 1.0,
                y: 2.0,
                z: 3.0,
            };
            unsafe { per_player(player, at, &mut self.report) };
            // Set on the NPC by `in_valid_state`; its sync has gone out.
            let action = unsafe { omp::player_action(player) };
            self.report
                .round_trip("player_action getter (from the NPC's sync)", 0, 1, action);
            let held = unsafe { omp::npc_weapon(npc.npc) };
            let weapon = unsafe { omp::player_armed_weapon(player) };
            self.report.round_trip(
                &format!("player_armed_weapon getter (from the NPC's sync; the NPC holds {held})"),
                0,
                24,
                weapon,
            );
        }
        // A connected NPC keeps the server from shutting down cleanly, and
        // destroying it is one more wrapper exercised.
        self.report.begin("npcs_destroy");
        unsafe { omp::npcs_destroy(npc.component, npc.npc) };
        self.finish();
    }
}

/// What needs the vehicle to have registered the NPC as its driver.
///
/// # Safety
/// The NPC and its vehicle must be live.
unsafe fn with_driver(npc: &Npc, report: &mut Report) {
    if npc.vehicle.is_null() {
        return;
    }
    unsafe {
        // Kept only with a driver (`Vehicle::setAngularVelocity`); linear
        // velocity needs one too but is only sent to the client.
        let spin = Vector3 {
            x: 0.0,
            y: 0.0,
            z: 0.5,
        };
        omp::vehicle_set_angular_velocity(npc.vehicle, spin);
        let got = omp::vehicle_angular_velocity(npc.vehicle);
        report.round_trip(
            "vehicle_angular_velocity (with a driver)",
            Vector3::ZERO,
            spin,
            got,
        );

        let left = omp::npc_remove_from_vehicle(npc.npc);
        report.check("npc_remove_from_vehicle", left, "refused");

        // Armed only now: the NPC's real spawn happens after it connects, and
        // `NPC::spawn` ends with `setWeapon(PlayerWeapon_Fist)` — a weapon given
        // before that is taken away again. On foot, its next sync reports it.
        omp::npc_set_weapon(npc.npc, 24);
        omp::npc_set_ammo(npc.npc, 50);
    }
}

impl Showcase {
    fn finish(&mut self) {
        self.finished = true;
        info!("[showcase] done");
        self.report.log();
    }
}

/// Creates one of everything that can be created and exercises it. Returns
/// the NPC, when one could be created, for the per-player part.
///
/// # Safety
/// Called once the server has every component ready.
#[allow(clippy::too_many_lines)]
unsafe fn exercise(report: &mut Report) -> Option<Npc> {
    let at = Vector3 {
        x: 1.0,
        y: 2.0,
        z: 3.0,
    };

    if let Some(core) = samp::plugin::omp_core() {
        unsafe { round_trips::round_trips_core(core, report) };
    }

    if let Some(c) = omp_query::<Component<omp::IObjectsComponent>>() {
        unsafe { round_trips::round_trips_objects_component(c.as_ptr(), report) };
        let object = unsafe { omp::create_object(c.as_ptr(), 1337, at, Vector3::ZERO, 0.0) };
        report.check("create_object", !object.is_null(), "null");
        if !object.is_null() {
            report.check(
                "object_model",
                unsafe { omp::object_model(object) } == 1337,
                unsafe { omp::object_model(object) },
            );
            unsafe { round_trips::round_trips_object(object, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IPickupsComponent>>() {
        let pickup = unsafe { omp::create_pickup(c.as_ptr(), 1274, 1, at, 0, false) };
        report.check("create_pickup", !pickup.is_null(), "null");
        if !pickup.is_null() {
            report.check(
                "pickup_model",
                unsafe { omp::pickup_model(pickup) } == 1274,
                unsafe { omp::pickup_model(pickup) },
            );
            // `setModel(id, update)` takes two arguments, so it is no round trip
            // of the generated kind; the same idea, by hand.
            unsafe { omp::pickup_set_model(pickup, 1275, true) };
            report.check(
                "pickup_set_model",
                unsafe { omp::pickup_model(pickup) } == 1275,
                unsafe { omp::pickup_model(pickup) },
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IVehiclesComponent>>() {
        let vehicle = unsafe { omp::create_vehicle(c.as_ptr(), 411, at, 0.0, -1, -1, -1, false) };
        report.check("create_vehicle", !vehicle.is_null(), "null");
        if !vehicle.is_null() {
            unsafe { round_trips::round_trips_vehicle(vehicle, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextDrawsComponent>>() {
        let td =
            unsafe { omp::create_textdraw(c.as_ptr(), Vector2 { x: 100.0, y: 100.0 }, "showcase") };
        report.check("create_textdraw", !td.is_null(), "null");
        if !td.is_null() {
            unsafe { omp::textdraw_set_text(td, StringView::of("showcase, again")) };
            // Getters with nothing to set them from: they must answer without
            // crashing, and the defaults a fresh text draw has are known.
            report.check(
                "textdraw_has_box",
                !unsafe { omp::textdraw_has_box(td) },
                "box on a new text draw",
            );
            report.check(
                "textdraw_is_selectable",
                !unsafe { omp::textdraw_is_selectable(td) },
                "selectable",
            );
            unsafe { round_trips::round_trips_text_draw(td, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IGangZonesComponent>>() {
        let area = omp::GangZonePos {
            min: Vector2 { x: 0.0, y: 0.0 },
            max: Vector2 { x: 10.0, y: 10.0 },
        };
        let zone = unsafe { omp::create_gangzone(c.as_ptr(), area) };
        report.check("create_gangzone", !zone.is_null(), "null");
    }

    if let Some(c) = omp_query::<Component<omp::IActorsComponent>>() {
        let actor = unsafe { omp::create_actor(c.as_ptr(), 46, at, 0.0) };
        report.check("create_actor", !actor.is_null(), "null");
        if !actor.is_null() {
            unsafe { round_trips::round_trips_actor(actor, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextLabelsComponent>>() {
        let white = omp::Colour::rgba(255, 255, 255, 255);
        let label =
            unsafe { omp::create_textlabel(c.as_ptr(), "showcase", white, at, 20.0, 0, false) };
        report.check("create_textlabel", !label.is_null(), "null");
        if !label.is_null() {
            unsafe { round_trips::round_trips_text_label(label, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IMenusComponent>>() {
        let origin = Vector2 { x: 50.0, y: 50.0 };
        let menu = unsafe { omp::create_menu(c.as_ptr(), "showcase", origin, 1, 100.0, 0.0) };
        report.check("create_menu", !menu.is_null(), "null");
        if !menu.is_null() {
            report.check(
                "menu_column_count",
                unsafe { omp::menu_column_count(menu) } == 1,
                unsafe { omp::menu_column_count(menu) },
            );
            report.check(
                "menu_is_enabled",
                unsafe { omp::menu_is_enabled(menu) },
                "disabled",
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IClassesComponent>>() {
        let weapons = [omp::WeaponSlot::default(); omp::MAX_WEAPON_SLOTS];
        let class = unsafe { omp::create_class(c.as_ptr(), 46, 0, at, 0.0, &weapons) };
        report.check("create_class", !class.is_null(), "null");
    }

    // An NPC connects as a player, which is what lets the player-side wrappers
    // run here at all.
    if let Some(c) = omp_query::<Component<omp::INPCComponent>>() {
        let npc = unsafe { omp::npcs_create(c.as_ptr(), StringView::of("showcase_bot")) };
        report.check(
            "npcs_create",
            !npc.is_null(),
            "null — is max_bots above zero?",
        );
        if !npc.is_null() {
            unsafe { omp::npc_spawn(npc) };
            unsafe { round_trips::round_trips_npc(npc, report) };

            let player = unsafe { omp::npc_player(npc) };
            let mut vehicle = std::ptr::null_mut();
            report.check("npc_player", !player.is_null(), "null");
            if !player.is_null() {
                report.check(
                    "player_is_bot",
                    unsafe { omp::player_is_bot(player) },
                    "not a bot",
                );
                unsafe { round_trips::round_trips_player(player, report) };
                vehicle = unsafe { in_valid_state(npc, player, report) };
            }
            return Some(Npc {
                component: c.as_ptr(),
                npc,
                vehicle,
            });
        }
    }
    None
}

/// The setters the generic round trips report as ignored, exercised under the
/// conditions the server's own code sets for them. Each one's rule, from
/// open.mp's `player_impl.hpp` and `NPCs/NPC/npc.cpp`:
///
/// - a fighting style must be one of 4, 5, 6, 7, 15 or 16 — anything else is
///   dropped, and the generic round trip tries 3;
/// - `setAmmoInClip` keeps `min(ammo, clip size of the current weapon)`, and a
///   bare fist has a clip of 0;
/// - the NPC's vehicle state is stored only `if (isInVehicle())`.
///
/// `setAction`, `setArmedWeapon` and `setVelocity` are different: they only send
/// an RPC to the client, and the getters read what the client syncs back. An
/// NPC's sync carries its own weapon and special action and ignores those RPCs,
/// so for an NPC-backed player the getters are proven the other way round: the
/// NPC sets them, and [`Showcase`] reads them back from the player afterwards.
///
/// # Safety
/// `npc` and `player` must be live, and the same NPC.
unsafe fn in_valid_state(
    npc: *mut omp::INPC,
    player: *mut omp::IPlayer,
    report: &mut Report,
) -> *mut omp::IVehicle {
    unsafe {
        omp::npc_set_fighting_style(npc, 5); // Boxing
        report.round_trip(
            "npc_fighting_style (valid)",
            4,
            5,
            omp::npc_fighting_style(npc),
        );
        omp::player_set_fighting_style(player, 6); // KungFu
        report.round_trip(
            "player_fighting_style (valid)",
            5,
            6,
            omp::player_fighting_style(player),
        );

        omp::npc_set_weapon(npc, 24); // Desert Eagle, a clip of 7
        omp::npc_set_ammo(npc, 50);
        omp::npc_set_ammo_in_clip(npc, 3);
        report.round_trip("npc_ammo_in_clip (armed)", 0, 3, omp::npc_ammo_in_clip(npc));
        // And the clamp the source describes: more than a clip is a full clip.
        omp::npc_set_ammo_in_clip(npc, 100);
        let clip = omp::npc_weapon_actual_clip_size(npc, 24);
        report.round_trip(
            "npc_ammo_in_clip (clamped)",
            3,
            clip,
            omp::npc_ammo_in_clip(npc),
        );
    }

    let Some(vehicles) = omp_query::<Component<omp::IVehiclesComponent>>() else {
        return std::ptr::null_mut();
    };
    let at = Vector3 {
        x: 5.0,
        y: 5.0,
        z: 3.0,
    };
    let vehicle =
        unsafe { omp::create_vehicle(vehicles.as_ptr(), 411, at, 0.0, -1, -1, -1, false) };
    if vehicle.is_null() {
        report.check("vehicle for the NPC", false, "null");
        return vehicle;
    }
    unsafe {
        let seated = omp::npc_put_in_vehicle(npc, vehicle, 0);
        report.check("npc_put_in_vehicle", seated, "refused");
        report.check(
            "npc_vehicle",
            omp::npc_vehicle(npc) == vehicle,
            omp::npc_vehicle(npc),
        );

        omp::npc_set_vehicle_gear_state(npc, 1);
        report.round_trip(
            "npc_vehicle_gear_state (in a vehicle)",
            0,
            1,
            omp::npc_vehicle_gear_state(npc),
        );
        omp::npc_set_vehicle_health(npc, 500.0);
        report.round_trip(
            "npc_vehicle_health (in a vehicle)",
            0.0,
            500.0,
            omp::npc_vehicle_health(npc),
        );
        omp::npc_set_vehicle_hydra_thrusters(npc, 2);
        report.round_trip(
            "npc_vehicle_hydra_thrusters (in a vehicle)",
            0,
            2,
            omp::npc_vehicle_hydra_thrusters(npc),
        );
        omp::npc_set_vehicle_train_speed(npc, 1.5);
        report.round_trip(
            "npc_vehicle_train_speed (in a vehicle)",
            0.0,
            1.5,
            omp::npc_vehicle_train_speed(npc),
        );
        // The NPC's setter also writes the vehicle's own health.
        report.round_trip(
            "vehicle_health (through the NPC)",
            1000.0,
            500.0,
            omp::vehicle_health(vehicle),
        );

        // The player's action and weapon come from the NPC's own sync, which
        // ignores the player-level RPCs: set them on the NPC, and read them
        // back from the player once a sync has gone out — see `on_tick`.
        omp::npc_set_special_action(npc, 1); // SpecialAction_Duck
        let _ = player;
    }
    // Left in the vehicle: its `driver` is set when the NPC's first driver sync
    // arrives, and angular velocity is only kept with a driver — `on_tick`.
    vehicle
}

/// The per-player extensions, reached through the player's extension map.
///
/// # Safety
/// `player` must be a live `IPlayer`.
unsafe fn per_player(player: *mut omp::IPlayer, at: Vector3, report: &mut Report) {
    let objects = unsafe { omp::player_objects(player) };
    report.check("player_objects", !objects.is_null(), "no IPlayerObjectData");
    if !objects.is_null() {
        let object = unsafe { omp::player_objects_create(objects, 1337, at, Vector3::ZERO, 0.0) };
        report.check("player_objects_create", !object.is_null(), "null");
        if !object.is_null() {
            unsafe { round_trips::round_trips_player_object(object, report) };
        }
    }

    let checkpoints = unsafe { omp::player_checkpoints(player) };
    report.check(
        "player_checkpoints",
        !checkpoints.is_null(),
        "no IPlayerCheckpointData",
    );
    if !checkpoints.is_null() {
        let checkpoint = unsafe { omp::player_checkpoints_checkpoint(checkpoints) };
        let race = unsafe { omp::player_checkpoints_race_checkpoint(checkpoints) };
        report.check(
            "player_checkpoints_checkpoint",
            !checkpoint.is_null(),
            "null",
        );
        report.check(
            "player_checkpoints_race_checkpoint",
            !race.is_null(),
            "null",
        );
        if !checkpoint.is_null() {
            unsafe { round_trips::round_trips_checkpoint_data(checkpoint, report) };
        }
        if !race.is_null() {
            unsafe { round_trips::round_trips_race_checkpoint_data(race, report) };
        }
    }

    // The hand-written lookup must land on what the generated accessor found.
    let by_uid = unsafe { omp::player_extension(player, omp::PLAYER_OBJECTS_UID) };
    report.check(
        "player_extension",
        !by_uid.is_null() && by_uid == objects.cast::<u8>(),
        by_uid,
    );

    let menus = unsafe { omp::player_menus(player) };
    report.check("player_menus", !menus.is_null(), "no IPlayerMenuData");
    if !menus.is_null() {
        unsafe { round_trips::round_trips_player_menu_data(menus, report) };
    }
}

initialize_plugin!(
    natives: [],
    {
        samp::plugin::enable_tick();
        let _ = samp::enable_logger!();
        // Every call is announced at debug level, so a crash is attributable.
        samp::logger::set_level(log::LevelFilter::Debug);
        Showcase {
            report: Report::default(),
            npc: None,
            started: None,
            driven: false,
            finished: false,
        }
    }
);
