//! Exercises the generated open.mp wrappers against a running server.
//!
//! Every wrapper under `samp::omp` is generated from the SDK headers, and every
//! slot the official binaries let us check is checked by
//! `scripts/check-abi-slots.py --generated`. What that cannot see is whether a
//! call works: the argument types, the return convention, the stack the callee
//! cleans. This plugin creates one entity of each kind the server offers, reads
//! back what it created, and round-trips every setter that has a matching getter
//! (`round_trips.rs`, generated by `scripts/omp-roundtrip.py`).
//!
//! An NPC stands in for a player, so the player-side wrappers run against a real
//! `IPlayer`. The server needs `max_bots` above zero in `config.json` for it.
//!
//! Load it as a component on open.mp, on Linux and on Windows. The summary line
//! should read `0 wrong` on both, with the same counts.

use log::info;
use samp::omp::{Component, StringView, Vector2, Vector3};
use samp::plugin::omp_query;
use samp::prelude::*;
use samp::{initialize_plugin, omp};

mod report;
// Generated for every handle with a set/get pair. Two have no way in yet — a
// player text label is created by an overloaded `create`, left to hand-written
// code, and the custom-models data has no generated accessor — so their round
// trips exist unused.
#[allow(clippy::all, clippy::pedantic, dead_code)]
mod round_trips;

use report::Report;

/// How long to wait before the per-player part. Components attach their
/// per-player data when the player connects, and an NPC created during
/// `on_omp_ready` connects through its own network afterwards.
const WAIT_BEFORE_PER_PLAYER: std::time::Duration = std::time::Duration::from_secs(3);

struct Showcase {
    report: Report,
    npc: Option<(*mut omp::INPCComponent, *mut omp::INPC)>,
    started: Option<std::time::Instant>,
    finished: bool,
}

impl SampPlugin for Showcase {
    fn on_omp_ready(&mut self) {
        self.npc = unsafe { exercise(&mut self.report) };
        if self.npc.is_none() {
            self.finish();
        }
    }

    fn on_tick(&mut self, _ctx: samp::plugin::TickContext) {
        if self.finished {
            return;
        }
        let started = *self.started.get_or_insert_with(std::time::Instant::now);
        if started.elapsed() < WAIT_BEFORE_PER_PLAYER {
            return;
        }
        if let Some((component, npc)) = self.npc.take() {
            let player = unsafe { omp::npc_player(npc) };
            if !player.is_null() {
                let at = Vector3 {
                    x: 1.0,
                    y: 2.0,
                    z: 3.0,
                };
                unsafe { per_player(player, at, &mut self.report) };
            }
            // A connected NPC keeps the server from shutting down cleanly, and
            // destroying it is one more wrapper exercised.
            self.report.begin("npcs_destroy");
            unsafe { omp::npcs_destroy(component, npc) };
        }
        self.finish();
    }
}

impl Showcase {
    fn finish(&mut self) {
        self.finished = true;
        info!("[showcase] done");
        self.report.log();
    }
}

/// Creates one of everything that can be created and exercises it. Returns
/// the NPC, when one could be created, for the per-player part.
///
/// # Safety
/// Called once the server has every component ready.
#[allow(clippy::too_many_lines)]
unsafe fn exercise(report: &mut Report) -> Option<(*mut omp::INPCComponent, *mut omp::INPC)> {
    let at = Vector3 {
        x: 1.0,
        y: 2.0,
        z: 3.0,
    };

    if let Some(core) = samp::plugin::omp_core() {
        unsafe { round_trips::round_trips_core(core, report) };
    }

    if let Some(c) = omp_query::<Component<omp::IObjectsComponent>>() {
        unsafe { round_trips::round_trips_objects_component(c.as_ptr(), report) };
        let object = unsafe { omp::create_object(c.as_ptr(), 1337, at, Vector3::ZERO, 0.0) };
        report.check("create_object", !object.is_null(), "null");
        if !object.is_null() {
            report.check(
                "object_model",
                unsafe { omp::object_model(object) } == 1337,
                unsafe { omp::object_model(object) },
            );
            unsafe { round_trips::round_trips_object(object, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IPickupsComponent>>() {
        let pickup = unsafe { omp::create_pickup(c.as_ptr(), 1274, 1, at, 0, false) };
        report.check("create_pickup", !pickup.is_null(), "null");
        if !pickup.is_null() {
            report.check(
                "pickup_model",
                unsafe { omp::pickup_model(pickup) } == 1274,
                unsafe { omp::pickup_model(pickup) },
            );
            // `setModel(id, update)` takes two arguments, so it is no round trip
            // of the generated kind; the same idea, by hand.
            unsafe { omp::pickup_set_model(pickup, 1275, true) };
            report.check(
                "pickup_set_model",
                unsafe { omp::pickup_model(pickup) } == 1275,
                unsafe { omp::pickup_model(pickup) },
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IVehiclesComponent>>() {
        let vehicle = unsafe { omp::create_vehicle(c.as_ptr(), 411, at, 0.0, -1, -1, -1, false) };
        report.check("create_vehicle", !vehicle.is_null(), "null");
        if !vehicle.is_null() {
            unsafe { round_trips::round_trips_vehicle(vehicle, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextDrawsComponent>>() {
        let td =
            unsafe { omp::create_textdraw(c.as_ptr(), Vector2 { x: 100.0, y: 100.0 }, "showcase") };
        report.check("create_textdraw", !td.is_null(), "null");
        if !td.is_null() {
            unsafe { omp::textdraw_set_text(td, StringView::of("showcase, again")) };
            // Getters with nothing to set them from: they must answer without
            // crashing, and the defaults a fresh text draw has are known.
            report.check(
                "textdraw_has_box",
                !unsafe { omp::textdraw_has_box(td) },
                "box on a new text draw",
            );
            report.check(
                "textdraw_is_selectable",
                !unsafe { omp::textdraw_is_selectable(td) },
                "selectable",
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IGangZonesComponent>>() {
        let area = omp::GangZonePos {
            min: Vector2 { x: 0.0, y: 0.0 },
            max: Vector2 { x: 10.0, y: 10.0 },
        };
        let zone = unsafe { omp::create_gangzone(c.as_ptr(), area) };
        report.check("create_gangzone", !zone.is_null(), "null");
    }

    if let Some(c) = omp_query::<Component<omp::IActorsComponent>>() {
        let actor = unsafe { omp::create_actor(c.as_ptr(), 46, at, 0.0) };
        report.check("create_actor", !actor.is_null(), "null");
        if !actor.is_null() {
            unsafe { round_trips::round_trips_actor(actor, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextLabelsComponent>>() {
        let white = omp::Colour::rgba(255, 255, 255, 255);
        let label =
            unsafe { omp::create_textlabel(c.as_ptr(), "showcase", white, at, 20.0, 0, false) };
        report.check("create_textlabel", !label.is_null(), "null");
        if !label.is_null() {
            unsafe { round_trips::round_trips_text_label(label, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IMenusComponent>>() {
        let origin = Vector2 { x: 50.0, y: 50.0 };
        let menu = unsafe { omp::create_menu(c.as_ptr(), "showcase", origin, 1, 100.0, 0.0) };
        report.check("create_menu", !menu.is_null(), "null");
        if !menu.is_null() {
            report.check(
                "menu_column_count",
                unsafe { omp::menu_column_count(menu) } == 1,
                unsafe { omp::menu_column_count(menu) },
            );
            report.check(
                "menu_is_enabled",
                unsafe { omp::menu_is_enabled(menu) },
                "disabled",
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IClassesComponent>>() {
        let weapons = [omp::WeaponSlot::default(); omp::MAX_WEAPON_SLOTS];
        let class = unsafe { omp::create_class(c.as_ptr(), 46, 0, at, 0.0, &weapons) };
        report.check("create_class", !class.is_null(), "null");
    }

    // An NPC connects as a player, which is what lets the player-side wrappers
    // run here at all.
    if let Some(c) = omp_query::<Component<omp::INPCComponent>>() {
        let npc = unsafe { omp::npcs_create(c.as_ptr(), StringView::of("showcase_bot")) };
        report.check(
            "npcs_create",
            !npc.is_null(),
            "null — is max_bots above zero?",
        );
        if !npc.is_null() {
            unsafe { omp::npc_spawn(npc) };
            unsafe { round_trips::round_trips_npc(npc, report) };

            let player = unsafe { omp::npc_player(npc) };
            report.check("npc_player", !player.is_null(), "null");
            if !player.is_null() {
                report.check(
                    "player_is_bot",
                    unsafe { omp::player_is_bot(player) },
                    "not a bot",
                );
                unsafe { round_trips::round_trips_player(player, report) };
            }
            return Some((c.as_ptr(), npc));
        }
    }
    None
}

/// The per-player extensions, reached through the player's extension map.
///
/// # Safety
/// `player` must be a live `IPlayer`.
unsafe fn per_player(player: *mut omp::IPlayer, at: Vector3, report: &mut Report) {
    let objects = unsafe { omp::player_objects(player) };
    report.check("player_objects", !objects.is_null(), "no IPlayerObjectData");
    if !objects.is_null() {
        let object = unsafe { omp::player_objects_create(objects, 1337, at, Vector3::ZERO, 0.0) };
        report.check("player_objects_create", !object.is_null(), "null");
        if !object.is_null() {
            unsafe { round_trips::round_trips_player_object(object, report) };
        }
    }

    let checkpoints = unsafe { omp::player_checkpoints(player) };
    report.check(
        "player_checkpoints",
        !checkpoints.is_null(),
        "no IPlayerCheckpointData",
    );
    if !checkpoints.is_null() {
        let checkpoint = unsafe { omp::player_checkpoints_checkpoint(checkpoints) };
        let race = unsafe { omp::player_checkpoints_race_checkpoint(checkpoints) };
        report.check(
            "player_checkpoints_checkpoint",
            !checkpoint.is_null(),
            "null",
        );
        report.check(
            "player_checkpoints_race_checkpoint",
            !race.is_null(),
            "null",
        );
        if !checkpoint.is_null() {
            unsafe { round_trips::round_trips_checkpoint_data(checkpoint, report) };
        }
        if !race.is_null() {
            unsafe { round_trips::round_trips_race_checkpoint_data(race, report) };
        }
    }

    // The hand-written lookup must land on what the generated accessor found.
    let by_uid = unsafe { omp::player_extension(player, omp::PLAYER_OBJECTS_UID) };
    report.check(
        "player_extension",
        !by_uid.is_null() && by_uid == objects.cast::<u8>(),
        by_uid,
    );

    let menus = unsafe { omp::player_menus(player) };
    report.check("player_menus", !menus.is_null(), "no IPlayerMenuData");
    if !menus.is_null() {
        unsafe { round_trips::round_trips_player_menu_data(menus, report) };
    }
}

initialize_plugin!(
    natives: [],
    {
        samp::plugin::enable_tick();
        let _ = samp::enable_logger!();
        // Every call is announced at debug level, so a crash is attributable.
        samp::logger::set_level(log::LevelFilter::Debug);
        Showcase {
            report: Report::default(),
            npc: None,
            started: None,
            finished: false,
        }
    }
);
