//! Exercises the generated open.mp wrappers against a running server.
//!
//! Every wrapper under `samp::omp` is generated from the SDK headers, and every
//! slot the official binaries let us check is checked by
//! `cargo xtask check-abi --generated`. What that cannot see is whether a
//! call works: the argument types, the return convention, the stack the callee
//! cleans. This plugin creates one entity of each kind the server offers, reads
//! back what it created, and round-trips every setter that has a matching getter
//! (`round_trips.rs`, generated by `cargo xtask roundtrip`).
//!
//! An NPC stands in for a player, so the player-side wrappers run against a real
//! `IPlayer`. The server needs `max_bots` above zero in `config.json` for it.
//!
//! Load it as a component on open.mp, on Linux and on Windows. The summary line
//! should read `0 wrong` on both, with the same counts.

use log::info;
use samp::omp::{Component, StringView, Vector2, Vector3};
use samp::plugin::omp_query;
use samp::prelude::*;
use samp::{initialize_plugin, omp};

mod events;
mod report;
// Generated for every handle with a set/get pair. The custom-models data has
// no generated accessor yet, so its round trips exist unused.
#[allow(clippy::all, clippy::pedantic, dead_code)]
mod round_trips;

use report::Report;

/// When the per-NPC checks run, counted from the first tick. The NPC connects
/// through its own network after `on_omp_ready`; its first driver sync sets the
/// vehicle's `driver`; components attach their per-player data on connect.
const DRIVER_SYNCED: std::time::Duration = std::time::Duration::from_secs(1);
const PLAYER_SYNCED: std::time::Duration = std::time::Duration::from_secs(3);

/// The NPC and what it was left with for the timed checks.
struct Npc {
    component: *mut omp::INPCComponent,
    npc: *mut omp::INPC,
    vehicle: *mut omp::IVehicle,
}

struct Showcase {
    report: Report,
    npc: Option<Npc>,
    started: Option<std::time::Instant>,
    driven: bool,
    /// When the NPC was destroyed: the server releases it on a later tick.
    destroyed: Option<std::time::Instant>,
    finished: bool,
}

impl SampPlugin for Showcase {
    fn on_omp_ready(&mut self) {
        self.npc = unsafe { exercise(&mut self.report) };
        if self.npc.is_none() {
            self.finish();
        }
    }

    fn on_tick(&mut self, _ctx: samp::plugin::TickContext) {
        if self.finished {
            return;
        }
        if let Some(at) = self.destroyed {
            if at.elapsed() >= std::time::Duration::from_millis(500) {
                let count = events::NPC_DESTROYED.load(std::sync::atomic::Ordering::Acquire);
                self.report.check(
                    "event on_npc_destroy [2] (released on a later tick)",
                    count == 1,
                    count,
                );
                self.finish();
            }
            return;
        }
        let elapsed = self
            .started
            .get_or_insert_with(std::time::Instant::now)
            .elapsed();
        let Some(npc) = self.npc.as_ref() else {
            return;
        };

        if !self.driven && elapsed >= DRIVER_SYNCED {
            self.driven = true;
            unsafe { with_driver(npc, &mut self.report) };
        }
        if elapsed < PLAYER_SYNCED {
            return;
        }

        let npc = self.npc.take().expect("checked above");
        let player = unsafe { omp::npc_player(npc.npc) };
        if !player.is_null() {
            let at = Vector3 {
                x: 1.0,
                y: 2.0,
                z: 3.0,
            };
            unsafe { per_player(player, at, &mut self.report) };
            // Set on the NPC by `in_valid_state`; its sync has gone out.
            let action = unsafe { omp::player_action(player) };
            self.report
                .round_trip("player_action getter (from the NPC's sync)", 0, 1, action);
            // The pool's set of bots, read from the hash table, holds the NPC.
            if let Some(core) = samp::plugin::omp_core() {
                let pool = unsafe { omp::player_pool(core) };
                let bots = unsafe { omp::flat_set_entries(omp::players_bots(pool)) };
                self.report
                    .check("players_bots (FlatSet)", bots.contains(&player), bots.len());
            }
            unsafe { omp::player_set_time(player, omp::Hours(12), omp::Minutes(30)) };
            let time = unsafe { omp::player_time(player) };
            self.report.check(
                "player_set_time / player_time (Pair)",
                time.is_some_and(|p| p.first == omp::Hours(12) && p.second == omp::Minutes(30)),
                time,
            );
            let skills = unsafe { omp::player_skill_levels(player) };
            self.report
                .check("player_skill_levels", !skills.is_null(), "null");
            let held = unsafe { omp::npc_weapon(npc.npc) };
            let weapon = unsafe { omp::player_armed_weapon(player) };
            self.report.round_trip(
                &format!("player_armed_weapon getter (from the NPC's sync; the NPC holds {held})"),
                0,
                24,
                weapon,
            );
        }
        // A connected NPC keeps the server from shutting down cleanly, and
        // destroying it is one more wrapper exercised.
        use std::sync::atomic::Ordering::Acquire;
        self.report.begin("npc_kill");
        unsafe { omp::npc_kill(npc.npc, std::ptr::null_mut(), 4) };
        self.report.begin("npcs_destroy");
        unsafe { omp::npcs_destroy(npc.component, npc.npc) };

        let r = &mut self.report;
        r.check(
            "event on_npc_create [1]",
            events::NPC_CREATED.load(Acquire) == 1,
            events::NPC_CREATED.load(Acquire),
        );
        r.check(
            "event on_npc_spawn [3]",
            events::NPC_SPAWNED.load(Acquire) >= 1,
            events::NPC_SPAWNED.load(Acquire),
        );
        r.check(
            "event on_npc_death [8]",
            events::NPC_DIED.load(Acquire) == 1
                && events::NPC_DEATH_REASON.load(Acquire) & 0xff == 4,
            (
                events::NPC_DIED.load(Acquire),
                events::NPC_DEATH_REASON.load(Acquire),
            ),
        );
        r.check(
            "event onPoolEntryCreated (player pool, generic template)",
            events::POOL_CREATED.load(Acquire) >= 1,
            events::POOL_CREATED.load(Acquire),
        );
        r.check(
            "event onTick (core: Microseconds, TimePoint by value)",
            events::CORE_TICKS.load(Acquire) > 10
                && events::CORE_TICKS_SANE.load(Acquire) == events::CORE_TICKS.load(Acquire),
            (
                events::CORE_TICKS.load(Acquire),
                events::CORE_TICKS_SANE.load(Acquire),
            ),
        );
        r.check(
            "timer fired three times (create_counted)",
            events::TIMER_FIRES.load(Acquire) == 3,
            events::TIMER_FIRES.load(Acquire),
        );
        r.check(
            "event on_moved [0]",
            events::OBJECT_MOVED.load(Acquire) >= 1,
            events::OBJECT_MOVED.load(Acquire),
        );
        self.destroyed = Some(std::time::Instant::now());
    }
}

/// What needs the vehicle to have registered the NPC as its driver.
///
/// # Safety
/// The NPC and its vehicle must be live.
unsafe fn with_driver(npc: &Npc, report: &mut Report) {
    if npc.vehicle.is_null() {
        return;
    }
    unsafe {
        // Kept only with a driver (`Vehicle::setAngularVelocity`); linear
        // velocity needs one too but is only sent to the client.
        let spin = Vector3 {
            x: 0.0,
            y: 0.0,
            z: 0.5,
        };
        omp::vehicle_set_angular_velocity(npc.vehicle, spin);
        let got = omp::vehicle_angular_velocity(npc.vehicle);
        report.round_trip(
            "vehicle_angular_velocity (with a driver)",
            Vector3::ZERO,
            spin,
            got,
        );

        let left = omp::npc_remove_from_vehicle(npc.npc);
        report.check("npc_remove_from_vehicle", left, "refused");

        // Armed only now: the NPC's real spawn happens after it connects, and
        // `NPC::spawn` ends with `setWeapon(PlayerWeapon_Fist)` — a weapon given
        // before that is taken away again. On foot, its next sync reports it.
        omp::npc_set_weapon(npc.npc, 24);
        omp::npc_set_ammo(npc.npc, 50);
    }
}

impl Showcase {
    fn finish(&mut self) {
        self.finished = true;
        info!("[showcase] done");
        self.report.log();
    }
}

/// Creates one of everything that can be created and exercises it. Returns
/// the NPC, when one could be created, for the per-player part.
///
/// # Safety
/// Called once the server has every component ready.
#[allow(clippy::too_many_lines)]
/// A counted timer: the component found through its `ComponentInterface`,
/// the four-argument `create`, and what the timer reports about itself. That
/// it fires exactly three times is checked when the run ends.
unsafe fn timers(report: &mut Report) {
    let Some((timer, handler)) = (unsafe { events::counted_timer() }) else {
        report.check("timers_create_counted", false, "no timer");
        return;
    };
    unsafe {
        report.check("timer_running", omp::timer_running(timer), "stopped");
        report.check(
            "timer_calls",
            omp::timer_calls(timer) == 3,
            omp::timer_calls(timer),
        );
        let interval = omp::timer_interval(timer);
        report.check(
            "timer_interval",
            interval == Some(omp::Milliseconds(100)),
            interval,
        );
        let remaining = omp::timer_remaining(timer);
        report.check(
            "timer_remaining",
            remaining.is_some_and(|r| (0..=100).contains(&r.0)),
            remaining,
        );
        report.check(
            "timer_handler",
            omp::timer_handler(timer) == handler,
            "another handler",
        );
        let component = omp_query::<Component<omp::ITimersComponent>>().map(|c| c.as_ptr());
        let count = component.map_or(0, |c| omp::timers_count(c));
        // The SDK's own tick timer, and this one.
        report.check("timers_count", count >= 2, count);
    }
}

/// The config: raw pointers back, a `Span` filled, a callback object called,
/// and a `BanEntry` — `HybridString`s inside — by reference.
unsafe fn config(report: &mut Report) {
    let Some(core) = samp::plugin::omp_core() else {
        return;
    };
    let config = unsafe { omp::core_config(core) };

    let bots = unsafe { omp::config_int(config, StringView::of("max_bots")) };
    report.check(
        "config_int",
        !bots.is_null() && unsafe { *bots } > 0,
        (!bots.is_null()).then(|| unsafe { *bots }),
    );

    let mut views = [StringView::EMPTY; 4];
    let count = unsafe {
        omp::config_strings(
            config,
            StringView::of("pawn.main_scripts"),
            omp::Span::of(&mut views),
        )
    };
    let first = (count >= 1)
        .then(|| unsafe { views[0].to_owned_string() })
        .flatten();
    report.check(
        "config_strings",
        first.as_deref().is_some_and(|s| !s.is_empty()),
        (count, first),
    );

    let mut enumerator = omp::OptionEnumeratorCallback::new(&raw const events::OPTION_VTABLE);
    unsafe { omp::config_enum_options(config, &raw mut enumerator) };
    let seen = events::OPTIONS_SEEN.load(std::sync::atomic::Ordering::Acquire);
    report.check("config_enum_options", seen > 10, seen);

    let ban = omp::BanEntry {
        address: omp::HybridString::new("10.20.30.40").unwrap_or_default(),
        time: omp::WorldTimePoint(0),
        name: omp::HybridString::new("showcase").unwrap_or_default(),
        reason: omp::HybridString::new("round trip").unwrap_or_default(),
    };
    unsafe { omp::config_add_ban(config, &ban) };
    let banned = unsafe { omp::config_is_banned(config, &ban) };
    unsafe { omp::config_remove_ban(config, &ban) };
    let after = unsafe { omp::config_is_banned(config, &ban) };
    report.check(
        "config_add_ban / is_banned / remove_ban",
        banned && !after,
        (banned, after),
    );
}

/// The mirrored structs, each through the call shape it travels in: by value,
/// by `const &`, and as a pointer into the server's own copy.
unsafe fn structs(npc: *mut omp::INPC, report: &mut Report) {
    let at = Vector3 {
        x: 5.0,
        y: 6.0,
        z: 7.0,
    };

    if let Some(c) = omp_query::<Component<omp::IVehiclesComponent>>() {
        let spawn = omp::VehicleSpawnData {
            respawn_delay: omp::Seconds(60),
            model_id: 522,
            position: at,
            z_rotation: 90.0,
            colour1: 3,
            colour2: 4,
            siren: false,
            interior: 0,
        };
        let vehicle = unsafe { omp::vehicles_create_from_spawn_data(c.as_ptr(), &spawn) };
        report.check(
            "vehicles_create_from_spawn_data",
            !vehicle.is_null(),
            "null",
        );
        if !vehicle.is_null() {
            let back = unsafe { omp::vehicle_spawn_data(vehicle) };
            report.check(
                "vehicle_spawn_data",
                !back.is_null() && unsafe { *back } == spawn,
                (!back.is_null()).then(|| unsafe { *back }),
            );

            // The quaternion's field order, against an angle the server keeps
            // separately: a yaw of 90 degrees has only `w` and `z` set, and a
            // wrong order would put them elsewhere.
            unsafe { omp::vehicle_set_z_angle(vehicle, 90.0) };
            let q = unsafe { omp::entity_rotation(vehicle.cast::<u8>()) };
            let half = std::f32::consts::FRAC_1_SQRT_2;
            report.check(
                "entity_rotation",
                (q.w.abs() - half).abs() < 1e-3
                    && (q.z.abs() - half).abs() < 1e-3
                    && q.x.abs() < 1e-3
                    && q.y.abs() < 1e-3,
                q,
            );
            let flat = omp::GTAQuat::IDENTITY;
            unsafe { omp::entity_set_rotation(vehicle.cast::<u8>(), flat) };
            let angle = unsafe { omp::vehicle_z_angle(vehicle) };
            report.check(
                "entity_set_rotation",
                angle.abs() < 1e-2 || (angle - 360.0).abs() < 1e-2,
                angle,
            );

            unsafe { omp::vehicle_set_colour(vehicle, 3, 4) };
            let colour = unsafe { omp::vehicle_colour(vehicle) };
            report.check(
                "vehicle_colour",
                colour.is_some_and(|p| (p.first, p.second) == (3, 4)),
                colour,
            );
            // `models()` counts vehicles per model, from 400: this one is 522.
            let models = unsafe { omp::vehicles_models(c.as_ptr()) };
            report.check(
                "vehicles_models",
                !models.is_null() && unsafe { (*models)[522 - 400] } >= 1,
                (!models.is_null()).then(|| unsafe { (*models)[522 - 400] }),
            );

            let params = omp::VehicleParams {
                engine: 1,
                lights: 0,
                ..omp::VehicleParams::default()
            };
            unsafe { omp::vehicle_set_params(vehicle, &params) };
            let read = unsafe { omp::vehicle_params(vehicle) };
            report.check(
                "vehicle_params",
                !read.is_null() && unsafe { *read } == params,
                (!read.is_null()).then(|| unsafe { *read }),
            );

            if let Some(labels) = omp_query::<Component<omp::ITextLabelsComponent>>() {
                let label = unsafe {
                    omp::textlabels_create_on_vehicle(
                        labels.as_ptr(),
                        StringView::of("on a vehicle"),
                        omp::Colour::rgba(255, 255, 255, 255),
                        Vector3::ZERO,
                        20.0,
                        0,
                        false,
                        vehicle,
                    )
                };
                report.check("textlabels_create_on_vehicle", !label.is_null(), "null");
                if !label.is_null() {
                    let data = unsafe { omp::textlabel_attachment_data(label) };
                    let id = unsafe { omp::vehicle_id(vehicle) };
                    report.check(
                        "textlabel_attachment_data",
                        !data.is_null() && unsafe { (*data).vehicle_id } == id,
                        (!data.is_null()).then(|| unsafe { *data }),
                    );
                }
            }
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextDrawsComponent>>() {
        let td =
            unsafe { omp::textdraws_create_preview(c.as_ptr(), Vector2 { x: 10.0, y: 10.0 }, 411) };
        report.check("textdraws_create_preview", !td.is_null(), "null");
        if !td.is_null() {
            report.check(
                "textdraw_preview_model",
                unsafe { omp::textdraw_preview_model(td) } == 411,
                unsafe { omp::textdraw_preview_model(td) },
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IGangZonesComponent>>() {
        let area = omp::GangZonePos {
            min: Vector2 { x: 0.0, y: 0.0 },
            max: Vector2 { x: 10.0, y: 10.0 },
        };
        let zone = unsafe { omp::create_gangzone(c.as_ptr(), area) };
        if !zone.is_null() {
            let moved = omp::GangZonePos {
                min: Vector2 { x: 1.0, y: 2.0 },
                max: Vector2 { x: 30.0, y: 40.0 },
            };
            unsafe { omp::gangzone_set_position(zone, &moved) };
            let got = unsafe { omp::gangzone_position(zone) };
            report.check("gangzone_position", got == moved, got);
        }
    }

    if let Some(c) = omp_query::<Component<omp::IObjectsComponent>>() {
        let object = unsafe { omp::create_object(c.as_ptr(), 1337, at, Vector3::ZERO, 0.0) };
        if !object.is_null() {
            let target = omp::ObjectMoveData {
                target_pos: Vector3 {
                    x: 50.0,
                    y: 60.0,
                    z: 70.0,
                },
                target_rot: Vector3::ZERO,
                speed: 1.0,
            };
            unsafe { omp::object_move(object, &target) };
            let moving = unsafe { omp::object_moving_data(object) };
            // A short, fast move of a second object: it arrives within a tick
            // or two, and `onMoved` reports it.
            let quick = unsafe { omp::create_object(c.as_ptr(), 1337, at, Vector3::ZERO, 0.0) };
            if !quick.is_null() {
                let near = omp::ObjectMoveData {
                    target_pos: Vector3 {
                        x: at.x + 1.0,
                        ..at
                    },
                    target_rot: Vector3::ZERO,
                    speed: 50.0,
                };
                unsafe { omp::object_move(quick, &near) };
            }
            report.check(
                "object_moving_data",
                !moving.is_null() && unsafe { (*moving).target_pos } == target.target_pos,
                (!moving.is_null()).then(|| unsafe { *moving }),
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IClassesComponent>>() {
        let weapons = [omp::WeaponSlot::default(); omp::MAX_WEAPON_SLOTS];
        let class = unsafe { omp::create_class(c.as_ptr(), 47, 2, at, 0.0, &weapons) };
        if !class.is_null() {
            let data = unsafe { omp::class_class(class) };
            report.check(
                "class_class",
                !data.is_null() && unsafe { ((*data).skin, (*data).team) } == (47, 2),
                (!data.is_null()).then(|| unsafe { ((*data).skin, (*data).team) }),
            );
        }
    }

    if !npc.is_null() {
        // A quarter turn about z, already normalised.
        let half = std::f32::consts::FRAC_1_SQRT_2;
        let turn = omp::GTAQuat {
            w: half,
            x: 0.0,
            y: 0.0,
            z: half,
        };
        unsafe { omp::npc_set_rotation(npc, &turn, true) };
        let got = unsafe { omp::npc_rotation(npc) };
        let close = [got.w - turn.w, got.x, got.y, got.z - turn.z]
            .iter()
            .all(|d| d.abs() < 1e-3);
        report.check("npc_rotation", close, got);
    }
}

unsafe fn exercise(report: &mut Report) -> Option<Npc> {
    // Found through the `ComponentInterface` impl the generator now writes
    // for it: its UID and where its `IComponent` sits.
    report.check(
        "omp_query (IDatabasesComponent)",
        omp_query::<Component<omp::IDatabasesComponent>>().is_some(),
        "not found",
    );
    let (tick_handler, pool_handler) = unsafe { events::register_core() };
    report.check("add_event_handler (core tick)", tick_handler, "refused");
    report.check("add_event_handler (player pool)", pool_handler, "refused");
    unsafe { config(report) };
    unsafe { timers(report) };
    let (npc_handler, object_handler) = unsafe { events::register() };
    report.check("add_event_handler (NPC)", npc_handler, "refused");
    report.check("add_event_handler (object)", object_handler, "refused");

    let at = Vector3 {
        x: 1.0,
        y: 2.0,
        z: 3.0,
    };

    if let Some(core) = samp::plugin::omp_core() {
        unsafe { round_trips::round_trips_core(core, report) };
        // A small struct returned through the hidden pointer, with an
        // argument after it.
        let config = unsafe { omp::core_config(core) };
        let server = unsafe { omp::config_string(config, StringView::of("name")) };
        report.check(
            "config_string",
            server.as_deref().is_some_and(|n| !n.is_empty()),
            server,
        );
        let name = unsafe { omp::core_weapon_name(core, 24) };
        report.check(
            "core_weapon_name",
            name.as_deref() == Some("Desert Eagle"),
            name,
        );
    }

    if let Some(c) = omp_query::<Component<omp::IObjectsComponent>>() {
        unsafe { round_trips::round_trips_objects_component(c.as_ptr(), report) };
        let object = unsafe { omp::create_object(c.as_ptr(), 1337, at, Vector3::ZERO, 0.0) };
        report.check("create_object", !object.is_null(), "null");
        if !object.is_null() {
            report.check(
                "object_model",
                unsafe { omp::object_model(object) } == 1337,
                unsafe { omp::object_model(object) },
            );
            unsafe { round_trips::round_trips_object(object, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IPickupsComponent>>() {
        let pickup = unsafe { omp::create_pickup(c.as_ptr(), 1274, 1, at, 0, false) };
        report.check("create_pickup", !pickup.is_null(), "null");
        if !pickup.is_null() {
            report.check(
                "pickup_model",
                unsafe { omp::pickup_model(pickup) } == 1274,
                unsafe { omp::pickup_model(pickup) },
            );
            // `setModel(id, update)` takes two arguments, so it is no round trip
            // of the generated kind; the same idea, by hand.
            unsafe { omp::pickup_set_model(pickup, 1275, true) };
            report.check(
                "pickup_set_model",
                unsafe { omp::pickup_model(pickup) } == 1275,
                unsafe { omp::pickup_model(pickup) },
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IVehiclesComponent>>() {
        let vehicle = unsafe { omp::create_vehicle(c.as_ptr(), 411, at, 0.0, -1, -1, -1, false) };
        report.check("create_vehicle", !vehicle.is_null(), "null");
        if !vehicle.is_null() {
            unsafe { round_trips::round_trips_vehicle(vehicle, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextDrawsComponent>>() {
        let td =
            unsafe { omp::create_textdraw(c.as_ptr(), Vector2 { x: 100.0, y: 100.0 }, "showcase") };
        report.check("create_textdraw", !td.is_null(), "null");
        if !td.is_null() {
            unsafe { omp::textdraw_set_text(td, StringView::of("showcase, again")) };
            // Getters with nothing to set them from: they must answer without
            // crashing, and the defaults a fresh text draw has are known.
            report.check(
                "textdraw_has_box",
                !unsafe { omp::textdraw_has_box(td) },
                "box on a new text draw",
            );
            report.check(
                "textdraw_is_selectable",
                !unsafe { omp::textdraw_is_selectable(td) },
                "selectable",
            );
            unsafe { round_trips::round_trips_text_draw(td, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IGangZonesComponent>>() {
        let area = omp::GangZonePos {
            min: Vector2 { x: 0.0, y: 0.0 },
            max: Vector2 { x: 10.0, y: 10.0 },
        };
        let zone = unsafe { omp::create_gangzone(c.as_ptr(), area) };
        report.check("create_gangzone", !zone.is_null(), "null");
    }

    if let Some(c) = omp_query::<Component<omp::IActorsComponent>>() {
        let actor = unsafe { omp::create_actor(c.as_ptr(), 46, at, 0.0) };
        report.check("create_actor", !actor.is_null(), "null");
        if !actor.is_null() {
            unsafe { round_trips::round_trips_actor(actor, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::ITextLabelsComponent>>() {
        let white = omp::Colour::rgba(255, 255, 255, 255);
        let label =
            unsafe { omp::create_textlabel(c.as_ptr(), "showcase", white, at, 20.0, 0, false) };
        report.check("create_textlabel", !label.is_null(), "null");
        if !label.is_null() {
            unsafe { round_trips::round_trips_text_label(label, report) };
        }
    }

    if let Some(c) = omp_query::<Component<omp::IMenusComponent>>() {
        let origin = Vector2 { x: 50.0, y: 50.0 };
        let menu = unsafe { omp::create_menu(c.as_ptr(), "showcase", origin, 1, 100.0, 0.0) };
        report.check("create_menu", !menu.is_null(), "null");
        if !menu.is_null() {
            report.check(
                "menu_column_count",
                unsafe { omp::menu_column_count(menu) } == 1,
                unsafe { omp::menu_column_count(menu) },
            );
            report.check(
                "menu_is_enabled",
                unsafe { omp::menu_is_enabled(menu) },
                "disabled",
            );
        }
    }

    if let Some(c) = omp_query::<Component<omp::IClassesComponent>>() {
        let weapons = [omp::WeaponSlot::default(); omp::MAX_WEAPON_SLOTS];
        let class = unsafe { omp::create_class(c.as_ptr(), 46, 0, at, 0.0, &weapons) };
        report.check("create_class", !class.is_null(), "null");
    }

    // An NPC connects as a player, which is what lets the player-side wrappers
    // run here at all.
    if let Some(c) = omp_query::<Component<omp::INPCComponent>>() {
        let npc = unsafe { omp::npcs_create(c.as_ptr(), StringView::of("showcase_bot")) };
        report.check(
            "npcs_create",
            !npc.is_null(),
            "null — is max_bots above zero?",
        );
        if !npc.is_null() {
            unsafe { omp::npc_spawn(npc) };
            unsafe { round_trips::round_trips_npc(npc, report) };
            unsafe { structs(npc, report) };

            let player = unsafe { omp::npc_player(npc) };
            let mut vehicle = std::ptr::null_mut();
            report.check("npc_player", !player.is_null(), "null");
            if !player.is_null() {
                report.check(
                    "player_is_bot",
                    unsafe { omp::player_is_bot(player) },
                    "not a bot",
                );
                unsafe { round_trips::round_trips_player(player, report) };
                vehicle = unsafe { in_valid_state(npc, player, report) };
            }
            return Some(Npc {
                component: c.as_ptr(),
                npc,
                vehicle,
            });
        }
    }
    None
}

/// The setters the generic round trips report as ignored, exercised under the
/// conditions the server's own code sets for them. Each one's rule, from
/// open.mp's `player_impl.hpp` and `NPCs/NPC/npc.cpp`:
///
/// - a fighting style must be one of 4, 5, 6, 7, 15 or 16 — anything else is
///   dropped, and the generic round trip tries 3;
/// - `setAmmoInClip` keeps `min(ammo, clip size of the current weapon)`, and a
///   bare fist has a clip of 0;
/// - the NPC's vehicle state is stored only `if (isInVehicle())`.
///
/// `setAction`, `setArmedWeapon` and `setVelocity` are different: they only send
/// an RPC to the client, and the getters read what the client syncs back. An
/// NPC's sync carries its own weapon and special action and ignores those RPCs,
/// so for an NPC-backed player the getters are proven the other way round: the
/// NPC sets them, and [`Showcase`] reads them back from the player afterwards.
///
/// # Safety
/// `npc` and `player` must be live, and the same NPC.
unsafe fn in_valid_state(
    npc: *mut omp::INPC,
    player: *mut omp::IPlayer,
    report: &mut Report,
) -> *mut omp::IVehicle {
    unsafe {
        omp::npc_set_fighting_style(npc, 5); // Boxing
        report.round_trip(
            "npc_fighting_style (valid)",
            4,
            5,
            omp::npc_fighting_style(npc),
        );
        omp::player_set_fighting_style(player, 6); // KungFu
        report.round_trip(
            "player_fighting_style (valid)",
            5,
            6,
            omp::player_fighting_style(player),
        );

        omp::npc_set_weapon(npc, 24); // Desert Eagle, a clip of 7
        omp::npc_set_ammo(npc, 50);
        omp::npc_set_ammo_in_clip(npc, 3);
        report.round_trip("npc_ammo_in_clip (armed)", 0, 3, omp::npc_ammo_in_clip(npc));
        // And the clamp the source describes: more than a clip is a full clip.
        omp::npc_set_ammo_in_clip(npc, 100);
        let clip = omp::npc_weapon_actual_clip_size(npc, 24);
        report.round_trip(
            "npc_ammo_in_clip (clamped)",
            3,
            clip,
            omp::npc_ammo_in_clip(npc),
        );
    }

    let Some(vehicles) = omp_query::<Component<omp::IVehiclesComponent>>() else {
        return std::ptr::null_mut();
    };
    let at = Vector3 {
        x: 5.0,
        y: 5.0,
        z: 3.0,
    };
    let vehicle =
        unsafe { omp::create_vehicle(vehicles.as_ptr(), 411, at, 0.0, -1, -1, -1, false) };
    if vehicle.is_null() {
        report.check("vehicle for the NPC", false, "null");
        return vehicle;
    }
    unsafe {
        let seated = omp::npc_put_in_vehicle(npc, vehicle, 0);
        report.check("npc_put_in_vehicle", seated, "refused");
        report.check(
            "npc_vehicle",
            omp::npc_vehicle(npc) == vehicle,
            omp::npc_vehicle(npc),
        );

        omp::npc_set_vehicle_gear_state(npc, 1);
        report.round_trip(
            "npc_vehicle_gear_state (in a vehicle)",
            0,
            1,
            omp::npc_vehicle_gear_state(npc),
        );
        omp::npc_set_vehicle_health(npc, 500.0);
        report.round_trip(
            "npc_vehicle_health (in a vehicle)",
            0.0,
            500.0,
            omp::npc_vehicle_health(npc),
        );
        omp::npc_set_vehicle_hydra_thrusters(npc, 2);
        report.round_trip(
            "npc_vehicle_hydra_thrusters (in a vehicle)",
            0,
            2,
            omp::npc_vehicle_hydra_thrusters(npc),
        );
        omp::npc_set_vehicle_train_speed(npc, 1.5);
        report.round_trip(
            "npc_vehicle_train_speed (in a vehicle)",
            0.0,
            1.5,
            omp::npc_vehicle_train_speed(npc),
        );
        // The NPC's setter also writes the vehicle's own health.
        report.round_trip(
            "vehicle_health (through the NPC)",
            1000.0,
            500.0,
            omp::vehicle_health(vehicle),
        );

        // The player's action and weapon come from the NPC's own sync, which
        // ignores the player-level RPCs: set them on the NPC, and read them
        // back from the player once a sync has gone out — see `on_tick`.
        omp::npc_set_special_action(npc, 1); // SpecialAction_Duck
        let _ = player;
    }
    // Left in the vehicle: its `driver` is set when the NPC's first driver sync
    // arrives, and angular velocity is only kept with a driver — `on_tick`.
    vehicle
}

/// The per-player extensions, reached through the player's extension map.
///
/// # Safety
/// `player` must be a live `IPlayer`.
unsafe fn per_player(player: *mut omp::IPlayer, at: Vector3, report: &mut Report) {
    let objects = unsafe { omp::player_objects(player) };
    report.check("player_objects", !objects.is_null(), "no IPlayerObjectData");
    if !objects.is_null() {
        let object = unsafe { omp::player_objects_create(objects, 1337, at, Vector3::ZERO, 0.0) };
        report.check("player_objects_create", !object.is_null(), "null");
        if !object.is_null() {
            unsafe { round_trips::round_trips_player_object(object, report) };
        }
    }

    let checkpoints = unsafe { omp::player_checkpoints(player) };
    report.check(
        "player_checkpoints",
        !checkpoints.is_null(),
        "no IPlayerCheckpointData",
    );
    if !checkpoints.is_null() {
        let checkpoint = unsafe { omp::player_checkpoints_checkpoint(checkpoints) };
        let race = unsafe { omp::player_checkpoints_race_checkpoint(checkpoints) };
        report.check(
            "player_checkpoints_checkpoint",
            !checkpoint.is_null(),
            "null",
        );
        report.check(
            "player_checkpoints_race_checkpoint",
            !race.is_null(),
            "null",
        );
        if !checkpoint.is_null() {
            unsafe { round_trips::round_trips_checkpoint_data(checkpoint, report) };
        }
        if !race.is_null() {
            unsafe { round_trips::round_trips_race_checkpoint_data(race, report) };
        }
    }

    // The hand-written lookup must land on what the generated accessor found.
    let by_uid = unsafe { omp::player_extension(player, omp::PLAYER_OBJECTS_UID) };
    report.check(
        "player_extension",
        !by_uid.is_null() && by_uid == objects.cast::<u8>(),
        by_uid,
    );

    // Created through an overload of `create`, each named in the TOML.
    let textdraws = unsafe { omp::player_textdraws(player) };
    report.check(
        "player_textdraws",
        !textdraws.is_null(),
        "no IPlayerTextDrawData",
    );
    if !textdraws.is_null() {
        let td = unsafe {
            omp::player_textdraws_create(
                textdraws,
                Vector2 { x: 100.0, y: 100.0 },
                StringView::of("showcase"),
            )
        };
        report.check("player_textdraws_create", !td.is_null(), "null");
        if !td.is_null() {
            unsafe { round_trips::round_trips_player_text_draw(td, report) };
        }
        let preview = unsafe {
            omp::player_textdraws_create_preview(textdraws, Vector2 { x: 50.0, y: 50.0 }, 411)
        };
        report.check(
            "player_textdraws_create_preview",
            !preview.is_null(),
            "null",
        );
        if !preview.is_null() {
            report.check(
                "player_textdraw_preview_model",
                unsafe { omp::player_textdraw_preview_model(preview) } == 411,
                unsafe { omp::player_textdraw_preview_model(preview) },
            );
        }
    }

    let labels = unsafe { omp::player_textlabels(player) };
    report.check(
        "player_textlabels",
        !labels.is_null(),
        "no IPlayerTextLabelData",
    );
    if !labels.is_null() {
        let label = unsafe {
            omp::player_textlabels_create(
                labels,
                StringView::of("showcase"),
                omp::Colour::rgba(255, 255, 255, 255),
                at,
                20.0,
                false,
            )
        };
        report.check("player_textlabels_create", !label.is_null(), "null");
        if !label.is_null() {
            unsafe { round_trips::round_trips_player_text_label(label, report) };
        }
    }

    let menus = unsafe { omp::player_menus(player) };
    report.check("player_menus", !menus.is_null(), "no IPlayerMenuData");
    if !menus.is_null() {
        unsafe { round_trips::round_trips_player_menu_data(menus, report) };
    }
}

initialize_plugin!(
    natives: [],
    {
        samp::plugin::enable_tick();
        let _ = samp::enable_logger!();
        // Every call is announced at debug level, so a crash is attributable.
        samp::logger::set_level(log::LevelFilter::Debug);
        Showcase {
            report: Report::default(),
            npc: None,
            started: None,
            driven: false,
            destroyed: None,
            finished: false,
        }
    }
);
