//! Set/get round trips over the generated wrappers — generated by
//! `scripts/omp-roundtrip.py`. Do not edit.

use samp::omp::*;

use crate::report::{Other, Report};

/// Every setter of `IActor` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IActor`.
pub unsafe fn round_trips_actor(handle: *mut IActor, report: &mut Report) {
    report.begin("actor_health");
    unsafe {
        let before: f32 = actor_health(handle);
        let want = before.other();
        actor_set_health(handle, want);
        report.round_trip("actor_health", before, want, actor_health(handle));
        actor_set_health(handle, before);
    }
    report.begin("actor_skin");
    unsafe {
        let before: i32 = actor_skin(handle);
        let want = before.other();
        actor_set_skin(handle, want);
        report.round_trip("actor_skin", before, want, actor_skin(handle));
        actor_set_skin(handle, before);
    }
}

/// Every setter of `ICheckpointData` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `ICheckpointData`.
pub unsafe fn round_trips_checkpoint_data(handle: *mut ICheckpointData, report: &mut Report) {
    report.begin("checkpoint_position");
    unsafe {
        let before: Vector3 = checkpoint_position(handle);
        let want = before.other();
        checkpoint_set_position(handle, &want);
        report.round_trip(
            "checkpoint_position",
            before,
            want,
            checkpoint_position(handle),
        );
        checkpoint_set_position(handle, &before);
    }
    report.begin("checkpoint_radius");
    unsafe {
        let before: f32 = checkpoint_radius(handle);
        let want = before.other();
        checkpoint_set_radius(handle, want);
        report.round_trip("checkpoint_radius", before, want, checkpoint_radius(handle));
        checkpoint_set_radius(handle, before);
    }
}

/// Every setter of `ICore` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `ICore`.
pub unsafe fn round_trips_core(handle: *mut ICore, report: &mut Report) {
    report.begin("core_gravity");
    unsafe {
        let before: f32 = core_gravity(handle);
        let want = before.other();
        core_set_gravity(handle, want);
        report.round_trip("core_gravity", before, want, core_gravity(handle));
        core_set_gravity(handle, before);
    }
}

/// Every setter of `INPC` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `INPC`.
pub unsafe fn round_trips_npc(handle: *mut INPC, report: &mut Report) {
    report.begin("npc_ammo");
    unsafe {
        let before: i32 = npc_ammo(handle);
        let want = before.other();
        npc_set_ammo(handle, want);
        report.round_trip("npc_ammo", before, want, npc_ammo(handle));
        npc_set_ammo(handle, before);
    }
    report.begin("npc_ammo_in_clip");
    unsafe {
        let before: i32 = npc_ammo_in_clip(handle);
        let want = before.other();
        npc_set_ammo_in_clip(handle, want);
        report.round_trip("npc_ammo_in_clip", before, want, npc_ammo_in_clip(handle));
        npc_set_ammo_in_clip(handle, before);
    }
    report.begin("npc_armour");
    unsafe {
        let before: f32 = npc_armour(handle);
        let want = before.other();
        npc_set_armour(handle, want);
        report.round_trip("npc_armour", before, want, npc_armour(handle));
        npc_set_armour(handle, before);
    }
    report.begin("npc_fighting_style");
    unsafe {
        let before: i32 = npc_fighting_style(handle);
        let want = before.other();
        npc_set_fighting_style(handle, want);
        report.round_trip(
            "npc_fighting_style",
            before,
            want,
            npc_fighting_style(handle),
        );
        npc_set_fighting_style(handle, before);
    }
    report.begin("npc_health");
    unsafe {
        let before: f32 = npc_health(handle);
        let want = before.other();
        npc_set_health(handle, want);
        report.round_trip("npc_health", before, want, npc_health(handle));
        npc_set_health(handle, before);
    }
    report.begin("npc_interior");
    unsafe {
        let before: u32 = npc_interior(handle);
        let want = before.other();
        npc_set_interior(handle, want);
        report.round_trip("npc_interior", before, want, npc_interior(handle));
        npc_set_interior(handle, before);
    }
    report.begin("npc_special_action");
    unsafe {
        let before: i32 = npc_special_action(handle);
        let want = before.other();
        npc_set_special_action(handle, want);
        report.round_trip(
            "npc_special_action",
            before,
            want,
            npc_special_action(handle),
        );
        npc_set_special_action(handle, before);
    }
    report.begin("npc_vehicle_gear_state");
    unsafe {
        let before: i32 = npc_vehicle_gear_state(handle);
        let want = before.other();
        npc_set_vehicle_gear_state(handle, want);
        report.round_trip(
            "npc_vehicle_gear_state",
            before,
            want,
            npc_vehicle_gear_state(handle),
        );
        npc_set_vehicle_gear_state(handle, before);
    }
    report.begin("npc_vehicle_health");
    unsafe {
        let before: f32 = npc_vehicle_health(handle);
        let want = before.other();
        npc_set_vehicle_health(handle, want);
        report.round_trip(
            "npc_vehicle_health",
            before,
            want,
            npc_vehicle_health(handle),
        );
        npc_set_vehicle_health(handle, before);
    }
    report.begin("npc_vehicle_hydra_thrusters");
    unsafe {
        let before: i32 = npc_vehicle_hydra_thrusters(handle);
        let want = before.other();
        npc_set_vehicle_hydra_thrusters(handle, want);
        report.round_trip(
            "npc_vehicle_hydra_thrusters",
            before,
            want,
            npc_vehicle_hydra_thrusters(handle),
        );
        npc_set_vehicle_hydra_thrusters(handle, before);
    }
    report.begin("npc_vehicle_train_speed");
    unsafe {
        let before: f32 = npc_vehicle_train_speed(handle);
        let want = before.other();
        npc_set_vehicle_train_speed(handle, want);
        report.round_trip(
            "npc_vehicle_train_speed",
            before,
            want,
            npc_vehicle_train_speed(handle),
        );
        npc_set_vehicle_train_speed(handle, before);
    }
    report.begin("npc_virtual_world");
    unsafe {
        let before: i32 = npc_virtual_world(handle);
        let want = before.other();
        npc_set_virtual_world(handle, want);
        report.round_trip("npc_virtual_world", before, want, npc_virtual_world(handle));
        npc_set_virtual_world(handle, before);
    }
    report.begin("npc_weapon");
    unsafe {
        let before: u8 = npc_weapon(handle);
        let want = before.other();
        npc_set_weapon(handle, want);
        report.round_trip("npc_weapon", before, want, npc_weapon(handle));
        npc_set_weapon(handle, before);
    }
    report.begin("npc_weapon_state");
    unsafe {
        let before: i8 = npc_weapon_state(handle);
        let want = before.other();
        npc_set_weapon_state(handle, want);
        report.round_trip("npc_weapon_state", before, want, npc_weapon_state(handle));
        npc_set_weapon_state(handle, before);
    }
}

/// Every setter of `IObject` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IObject`.
pub unsafe fn round_trips_object(handle: *mut IObject, report: &mut Report) {
    report.begin("object_camera_collision");
    unsafe {
        let before: bool = object_camera_collision(handle);
        let want = before.other();
        object_set_camera_collision(handle, want);
        report.round_trip(
            "object_camera_collision",
            before,
            want,
            object_camera_collision(handle),
        );
        object_set_camera_collision(handle, before);
    }
    report.begin("object_draw_distance");
    unsafe {
        let before: f32 = object_draw_distance(handle);
        let want = before.other();
        object_set_draw_distance(handle, want);
        report.round_trip(
            "object_draw_distance",
            before,
            want,
            object_draw_distance(handle),
        );
        object_set_draw_distance(handle, before);
    }
    report.begin("object_model");
    unsafe {
        let before: i32 = object_model(handle);
        let want = before.other();
        object_set_model(handle, want);
        report.round_trip("object_model", before, want, object_model(handle));
        object_set_model(handle, before);
    }
}

/// Every setter of `IObjectsComponent` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IObjectsComponent`.
pub unsafe fn round_trips_objects_component(handle: *mut IObjectsComponent, report: &mut Report) {
    report.begin("objects_default_camera_collision");
    unsafe {
        let before: bool = objects_default_camera_collision(handle);
        let want = before.other();
        objects_set_default_camera_collision(handle, want);
        report.round_trip(
            "objects_default_camera_collision",
            before,
            want,
            objects_default_camera_collision(handle),
        );
        objects_set_default_camera_collision(handle, before);
    }
}

/// Every setter of `IPlayer` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayer`.
pub unsafe fn round_trips_player(handle: *mut IPlayer, report: &mut Report) {
    report.begin("player_action");
    unsafe {
        let before: i32 = player_action(handle);
        let want = before.other();
        player_set_action(handle, want);
        report.round_trip("player_action", before, want, player_action(handle));
        player_set_action(handle, before);
    }
    report.begin("player_armed_weapon");
    unsafe {
        let before: u32 = player_armed_weapon(handle);
        let want = before.other();
        player_set_armed_weapon(handle, want);
        report.round_trip(
            "player_armed_weapon",
            before,
            want,
            player_armed_weapon(handle),
        );
        player_set_armed_weapon(handle, before);
    }
    report.begin("player_camera_position");
    unsafe {
        let before: Vector3 = player_camera_position(handle);
        let want = before.other();
        player_set_camera_position(handle, want);
        report.round_trip(
            "player_camera_position",
            before,
            want,
            player_camera_position(handle),
        );
        player_set_camera_position(handle, before);
    }
    report.begin("player_fighting_style");
    unsafe {
        let before: i32 = player_fighting_style(handle);
        let want = before.other();
        player_set_fighting_style(handle, want);
        report.round_trip(
            "player_fighting_style",
            before,
            want,
            player_fighting_style(handle),
        );
        player_set_fighting_style(handle, before);
    }
    report.begin("player_gravity");
    unsafe {
        let before: f32 = player_gravity(handle);
        let want = before.other();
        player_set_gravity(handle, want);
        report.round_trip("player_gravity", before, want, player_gravity(handle));
        player_set_gravity(handle, before);
    }
    report.begin("player_shop_name");
    unsafe {
        let before = player_shop_name(handle).unwrap_or_default();
        let want = before.other();
        player_set_shop_name(handle, StringView::of(&want));
        let got = player_shop_name(handle).unwrap_or_default();
        report.round_trip("player_shop_name", before.clone(), want, got);
        player_set_shop_name(handle, StringView::of(&before));
    }
    report.begin("player_velocity");
    unsafe {
        let before: Vector3 = player_velocity(handle);
        let want = before.other();
        player_set_velocity(handle, want);
        report.round_trip("player_velocity", before, want, player_velocity(handle));
        player_set_velocity(handle, before);
    }
    report.begin("player_world_bounds");
    unsafe {
        let before: Vector4 = player_world_bounds(handle);
        let want = before.other();
        player_set_world_bounds(handle, want);
        report.round_trip(
            "player_world_bounds",
            before,
            want,
            player_world_bounds(handle),
        );
        player_set_world_bounds(handle, before);
    }
}

/// Every setter of `IPlayerCustomModelsData` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayerCustomModelsData`.
pub unsafe fn round_trips_player_custom_models_data(
    handle: *mut IPlayerCustomModelsData,
    report: &mut Report,
) {
    report.begin("player_custom_models_custom_skin");
    unsafe {
        let before: u32 = player_custom_models_custom_skin(handle);
        let want = before.other();
        player_custom_models_set_custom_skin(handle, want);
        report.round_trip(
            "player_custom_models_custom_skin",
            before,
            want,
            player_custom_models_custom_skin(handle),
        );
        player_custom_models_set_custom_skin(handle, before);
    }
}

/// Every setter of `IPlayerMenuData` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayerMenuData`.
pub unsafe fn round_trips_player_menu_data(handle: *mut IPlayerMenuData, report: &mut Report) {
    report.begin("player_menus_menu_id");
    unsafe {
        let before: u8 = player_menus_menu_id(handle);
        let want = before.other();
        player_menus_set_menu_id(handle, want);
        report.round_trip(
            "player_menus_menu_id",
            before,
            want,
            player_menus_menu_id(handle),
        );
        player_menus_set_menu_id(handle, before);
    }
}

/// Every setter of `IPlayerObject` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayerObject`.
pub unsafe fn round_trips_player_object(handle: *mut IPlayerObject, report: &mut Report) {
    report.begin("player_object_camera_collision");
    unsafe {
        let before: bool = player_object_camera_collision(handle);
        let want = before.other();
        player_object_set_camera_collision(handle, want);
        report.round_trip(
            "player_object_camera_collision",
            before,
            want,
            player_object_camera_collision(handle),
        );
        player_object_set_camera_collision(handle, before);
    }
    report.begin("player_object_draw_distance");
    unsafe {
        let before: f32 = player_object_draw_distance(handle);
        let want = before.other();
        player_object_set_draw_distance(handle, want);
        report.round_trip(
            "player_object_draw_distance",
            before,
            want,
            player_object_draw_distance(handle),
        );
        player_object_set_draw_distance(handle, before);
    }
    report.begin("player_object_model");
    unsafe {
        let before: i32 = player_object_model(handle);
        let want = before.other();
        player_object_set_model(handle, want);
        report.round_trip(
            "player_object_model",
            before,
            want,
            player_object_model(handle),
        );
        player_object_set_model(handle, before);
    }
}

/// Every setter of `IPlayerTextDraw` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayerTextDraw`.
pub unsafe fn round_trips_player_text_draw(handle: *mut IPlayerTextDraw, report: &mut Report) {
    report.begin("player_textdraw_alignment");
    unsafe {
        let before: i32 = player_textdraw_alignment(handle);
        let want = before.other();
        player_textdraw_set_alignment(handle, want);
        report.round_trip(
            "player_textdraw_alignment",
            before,
            want,
            player_textdraw_alignment(handle),
        );
        player_textdraw_set_alignment(handle, before);
    }
    report.begin("player_textdraw_box_colour");
    unsafe {
        let before = player_textdraw_box_colour(handle).unwrap_or_default();
        let want = before.other();
        player_textdraw_set_box_colour(handle, want);
        report.round_trip(
            "player_textdraw_box_colour",
            before,
            want,
            player_textdraw_box_colour(handle).unwrap_or_default(),
        );
        player_textdraw_set_box_colour(handle, before);
    }
    report.begin("player_textdraw_outline");
    unsafe {
        let before: i32 = player_textdraw_outline(handle);
        let want = before.other();
        player_textdraw_set_outline(handle, want);
        report.round_trip(
            "player_textdraw_outline",
            before,
            want,
            player_textdraw_outline(handle),
        );
        player_textdraw_set_outline(handle, before);
    }
    report.begin("player_textdraw_preview_model");
    unsafe {
        let before: i32 = player_textdraw_preview_model(handle);
        let want = before.other();
        player_textdraw_set_preview_model(handle, want);
        report.round_trip(
            "player_textdraw_preview_model",
            before,
            want,
            player_textdraw_preview_model(handle),
        );
        player_textdraw_set_preview_model(handle, before);
    }
    report.begin("player_textdraw_preview_rotation");
    unsafe {
        let before: Vector3 = player_textdraw_preview_rotation(handle);
        let want = before.other();
        player_textdraw_set_preview_rotation(handle, want);
        report.round_trip(
            "player_textdraw_preview_rotation",
            before,
            want,
            player_textdraw_preview_rotation(handle),
        );
        player_textdraw_set_preview_rotation(handle, before);
    }
    report.begin("player_textdraw_preview_zoom");
    unsafe {
        let before: f32 = player_textdraw_preview_zoom(handle);
        let want = before.other();
        player_textdraw_set_preview_zoom(handle, want);
        report.round_trip(
            "player_textdraw_preview_zoom",
            before,
            want,
            player_textdraw_preview_zoom(handle),
        );
        player_textdraw_set_preview_zoom(handle, before);
    }
    report.begin("player_textdraw_shadow");
    unsafe {
        let before: i32 = player_textdraw_shadow(handle);
        let want = before.other();
        player_textdraw_set_shadow(handle, want);
        report.round_trip(
            "player_textdraw_shadow",
            before,
            want,
            player_textdraw_shadow(handle),
        );
        player_textdraw_set_shadow(handle, before);
    }
    report.begin("player_textdraw_style");
    unsafe {
        let before: i32 = player_textdraw_style(handle);
        let want = before.other();
        player_textdraw_set_style(handle, want);
        report.round_trip(
            "player_textdraw_style",
            before,
            want,
            player_textdraw_style(handle),
        );
        player_textdraw_set_style(handle, before);
    }
    report.begin("player_textdraw_text");
    unsafe {
        let before = player_textdraw_text(handle).unwrap_or_default();
        let want = before.other();
        player_textdraw_set_text(handle, StringView::of(&want));
        let got = player_textdraw_text(handle).unwrap_or_default();
        report.round_trip("player_textdraw_text", before.clone(), want, got);
        player_textdraw_set_text(handle, StringView::of(&before));
    }
}

/// Every setter of `IPlayerTextLabel` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IPlayerTextLabel`.
pub unsafe fn round_trips_player_text_label(handle: *mut IPlayerTextLabel, report: &mut Report) {
    report.begin("player_textlabel_colour");
    unsafe {
        let before = player_textlabel_colour(handle).unwrap_or_default();
        let want = before.other();
        player_textlabel_set_colour(handle, want);
        report.round_trip(
            "player_textlabel_colour",
            before,
            want,
            player_textlabel_colour(handle).unwrap_or_default(),
        );
        player_textlabel_set_colour(handle, before);
    }
    report.begin("player_textlabel_draw_distance");
    unsafe {
        let before: f32 = player_textlabel_draw_distance(handle);
        let want = before.other();
        player_textlabel_set_draw_distance(handle, want);
        report.round_trip(
            "player_textlabel_draw_distance",
            before,
            want,
            player_textlabel_draw_distance(handle),
        );
        player_textlabel_set_draw_distance(handle, before);
    }
    report.begin("player_textlabel_test_los");
    unsafe {
        let before: bool = player_textlabel_test_los(handle);
        let want = before.other();
        player_textlabel_set_test_los(handle, want);
        report.round_trip(
            "player_textlabel_test_los",
            before,
            want,
            player_textlabel_test_los(handle),
        );
        player_textlabel_set_test_los(handle, before);
    }
    report.begin("player_textlabel_text");
    unsafe {
        let before = player_textlabel_text(handle).unwrap_or_default();
        let want = before.other();
        player_textlabel_set_text(handle, StringView::of(&want));
        let got = player_textlabel_text(handle).unwrap_or_default();
        report.round_trip("player_textlabel_text", before.clone(), want, got);
        player_textlabel_set_text(handle, StringView::of(&before));
    }
}

/// Every setter of `IRaceCheckpointData` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IRaceCheckpointData`.
pub unsafe fn round_trips_race_checkpoint_data(
    handle: *mut IRaceCheckpointData,
    report: &mut Report,
) {
    report.begin("race_checkpoint_next_position");
    unsafe {
        let before: Vector3 = race_checkpoint_next_position(handle);
        let want = before.other();
        race_checkpoint_set_next_position(handle, &want);
        report.round_trip(
            "race_checkpoint_next_position",
            before,
            want,
            race_checkpoint_next_position(handle),
        );
        race_checkpoint_set_next_position(handle, &before);
    }
    report.begin("race_checkpoint_position");
    unsafe {
        let before: Vector3 = race_checkpoint_position(handle);
        let want = before.other();
        race_checkpoint_set_position(handle, &want);
        report.round_trip(
            "race_checkpoint_position",
            before,
            want,
            race_checkpoint_position(handle),
        );
        race_checkpoint_set_position(handle, &before);
    }
    report.begin("race_checkpoint_radius");
    unsafe {
        let before: f32 = race_checkpoint_radius(handle);
        let want = before.other();
        race_checkpoint_set_radius(handle, want);
        report.round_trip(
            "race_checkpoint_radius",
            before,
            want,
            race_checkpoint_radius(handle),
        );
        race_checkpoint_set_radius(handle, before);
    }
    report.begin("race_checkpoint_type");
    unsafe {
        let before: i32 = race_checkpoint_type(handle);
        let want = before.other();
        race_checkpoint_set_type(handle, want);
        report.round_trip(
            "race_checkpoint_type",
            before,
            want,
            race_checkpoint_type(handle),
        );
        race_checkpoint_set_type(handle, before);
    }
}

/// Every setter of `ITextDraw` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `ITextDraw`.
pub unsafe fn round_trips_text_draw(handle: *mut ITextDraw, report: &mut Report) {
    report.begin("textdraw_alignment");
    unsafe {
        let before: i32 = textdraw_alignment(handle);
        let want = before.other();
        textdraw_set_alignment(handle, want);
        report.round_trip(
            "textdraw_alignment",
            before,
            want,
            textdraw_alignment(handle),
        );
        textdraw_set_alignment(handle, before);
    }
    report.begin("textdraw_background_colour");
    unsafe {
        let before = textdraw_background_colour(handle).unwrap_or_default();
        let want = before.other();
        textdraw_set_background_colour(handle, want);
        report.round_trip(
            "textdraw_background_colour",
            before,
            want,
            textdraw_background_colour(handle).unwrap_or_default(),
        );
        textdraw_set_background_colour(handle, before);
    }
    report.begin("textdraw_box_colour");
    unsafe {
        let before = textdraw_box_colour(handle).unwrap_or_default();
        let want = before.other();
        textdraw_set_box_colour(handle, want);
        report.round_trip(
            "textdraw_box_colour",
            before,
            want,
            textdraw_box_colour(handle).unwrap_or_default(),
        );
        textdraw_set_box_colour(handle, before);
    }
    report.begin("textdraw_outline");
    unsafe {
        let before: i32 = textdraw_outline(handle);
        let want = before.other();
        textdraw_set_outline(handle, want);
        report.round_trip("textdraw_outline", before, want, textdraw_outline(handle));
        textdraw_set_outline(handle, before);
    }
    report.begin("textdraw_preview_model");
    unsafe {
        let before: i32 = textdraw_preview_model(handle);
        let want = before.other();
        textdraw_set_preview_model(handle, want);
        report.round_trip(
            "textdraw_preview_model",
            before,
            want,
            textdraw_preview_model(handle),
        );
        textdraw_set_preview_model(handle, before);
    }
    report.begin("textdraw_preview_rotation");
    unsafe {
        let before: Vector3 = textdraw_preview_rotation(handle);
        let want = before.other();
        textdraw_set_preview_rotation(handle, want);
        report.round_trip(
            "textdraw_preview_rotation",
            before,
            want,
            textdraw_preview_rotation(handle),
        );
        textdraw_set_preview_rotation(handle, before);
    }
    report.begin("textdraw_preview_zoom");
    unsafe {
        let before: f32 = textdraw_preview_zoom(handle);
        let want = before.other();
        textdraw_set_preview_zoom(handle, want);
        report.round_trip(
            "textdraw_preview_zoom",
            before,
            want,
            textdraw_preview_zoom(handle),
        );
        textdraw_set_preview_zoom(handle, before);
    }
    report.begin("textdraw_shadow");
    unsafe {
        let before: i32 = textdraw_shadow(handle);
        let want = before.other();
        textdraw_set_shadow(handle, want);
        report.round_trip("textdraw_shadow", before, want, textdraw_shadow(handle));
        textdraw_set_shadow(handle, before);
    }
    report.begin("textdraw_style");
    unsafe {
        let before: i32 = textdraw_style(handle);
        let want = before.other();
        textdraw_set_style(handle, want);
        report.round_trip("textdraw_style", before, want, textdraw_style(handle));
        textdraw_set_style(handle, before);
    }
    report.begin("textdraw_text");
    unsafe {
        let before = textdraw_text(handle).unwrap_or_default();
        let want = before.other();
        textdraw_set_text(handle, StringView::of(&want));
        let got = textdraw_text(handle).unwrap_or_default();
        report.round_trip("textdraw_text", before.clone(), want, got);
        textdraw_set_text(handle, StringView::of(&before));
    }
}

/// Every setter of `ITextLabel` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `ITextLabel`.
pub unsafe fn round_trips_text_label(handle: *mut ITextLabel, report: &mut Report) {
    report.begin("textlabel_colour");
    unsafe {
        let before = textlabel_colour(handle).unwrap_or_default();
        let want = before.other();
        textlabel_set_colour(handle, want);
        report.round_trip(
            "textlabel_colour",
            before,
            want,
            textlabel_colour(handle).unwrap_or_default(),
        );
        textlabel_set_colour(handle, before);
    }
    report.begin("textlabel_draw_distance");
    unsafe {
        let before: f32 = textlabel_draw_distance(handle);
        let want = before.other();
        textlabel_set_draw_distance(handle, want);
        report.round_trip(
            "textlabel_draw_distance",
            before,
            want,
            textlabel_draw_distance(handle),
        );
        textlabel_set_draw_distance(handle, before);
    }
    report.begin("textlabel_test_los");
    unsafe {
        let before: bool = textlabel_test_los(handle);
        let want = before.other();
        textlabel_set_test_los(handle, want);
        report.round_trip(
            "textlabel_test_los",
            before,
            want,
            textlabel_test_los(handle),
        );
        textlabel_set_test_los(handle, before);
    }
    report.begin("textlabel_text");
    unsafe {
        let before = textlabel_text(handle).unwrap_or_default();
        let want = before.other();
        textlabel_set_text(handle, StringView::of(&want));
        let got = textlabel_text(handle).unwrap_or_default();
        report.round_trip("textlabel_text", before.clone(), want, got);
        textlabel_set_text(handle, StringView::of(&before));
    }
}

/// Every setter of `IVehicle` that has a matching getter.
///
/// # Safety
/// `handle` must be a live `IVehicle`.
pub unsafe fn round_trips_vehicle(handle: *mut IVehicle, report: &mut Report) {
    report.begin("vehicle_angular_velocity");
    unsafe {
        let before: Vector3 = vehicle_angular_velocity(handle);
        let want = before.other();
        vehicle_set_angular_velocity(handle, want);
        report.round_trip(
            "vehicle_angular_velocity",
            before,
            want,
            vehicle_angular_velocity(handle),
        );
        vehicle_set_angular_velocity(handle, before);
    }
    report.begin("vehicle_interior");
    unsafe {
        let before: i32 = vehicle_interior(handle);
        let want = before.other();
        vehicle_set_interior(handle, want);
        report.round_trip("vehicle_interior", before, want, vehicle_interior(handle));
        vehicle_set_interior(handle, before);
    }
    report.begin("vehicle_paint_job");
    unsafe {
        let before: i32 = vehicle_paint_job(handle);
        let want = before.other();
        vehicle_set_paint_job(handle, want);
        report.round_trip("vehicle_paint_job", before, want, vehicle_paint_job(handle));
        vehicle_set_paint_job(handle, before);
    }
    report.begin("vehicle_plate");
    unsafe {
        let before = vehicle_plate(handle).unwrap_or_default();
        let want = before.other();
        vehicle_set_plate(handle, StringView::of(&want));
        let got = vehicle_plate(handle).unwrap_or_default();
        report.round_trip("vehicle_plate", before.clone(), want, got);
        vehicle_set_plate(handle, StringView::of(&before));
    }
    report.begin("vehicle_respawn_delay");
    unsafe {
        let before = vehicle_respawn_delay(handle).unwrap_or_default();
        let want = before.other();
        vehicle_set_respawn_delay(handle, want);
        report.round_trip(
            "vehicle_respawn_delay",
            before,
            want,
            vehicle_respawn_delay(handle).unwrap_or_default(),
        );
        vehicle_set_respawn_delay(handle, before);
    }
    report.begin("vehicle_velocity");
    unsafe {
        let before: Vector3 = vehicle_velocity(handle);
        let want = before.other();
        vehicle_set_velocity(handle, want);
        report.round_trip("vehicle_velocity", before, want, vehicle_velocity(handle));
        vehicle_set_velocity(handle, before);
    }
    report.begin("vehicle_z_angle");
    unsafe {
        let before: f32 = vehicle_z_angle(handle);
        let want = before.other();
        vehicle_set_z_angle(handle, want);
        report.round_trip("vehicle_z_angle", before, want, vehicle_z_angle(handle));
        vehicle_set_z_angle(handle, before);
    }
}
