//! Typed access to the `amx_*` functions exported by the server.
//!
//! The server exposes `amx_Exports` (passed in `Load()`) as a flat table of
//! pointers, indexed by the values of [`Exports`]. Each function has a
//! zero-sized marker type (generated by `impl_export!`) that carries the
//! corresponding offset in [`Export::OFFSET`] and the function type in [`Export::Output`].
//!
//! Typical usage: `Exec::from_table(fn_table)` returns the typed pointer.
//! Resolving on demand avoids storing all 44 pointers in [`crate::amx::Amx`].

use crate::raw::functions;

macro_rules! impl_export {
    ($name:ident) => {
        pub struct $name;

        impl Export for $name {
            type Output = functions::$name;
            const OFFSET: isize = Exports::$name as isize;

            #[inline(always)]
            fn from_table(fn_table: usize) -> Self::Output {
                assert!(fn_table != 0, "from_table() received null fn_table");
                let table = fn_table as *const usize;

                unsafe {
                    let ptr = table.offset(Self::OFFSET);
                    assert!(
                        ptr.read() != 0,
                        "from_table() function at offset {} is null",
                        Self::OFFSET
                    );
                    ptr.cast::<Self::Output>().read()
                }
            }
        }
    };
}

/// Retrieves a typed pointer from the `amx_Exports` table.
pub trait Export {
    /// Type of the exported function — alias declared in [`crate::raw::functions`].
    type Output;

    /// Offset of this function in the table. Values correspond 1:1 to [`Exports`].
    const OFFSET: isize;

    /// Reads the pointer at offset `OFFSET` of the `fn_table` table.
    ///
    /// # Panics
    /// In debug mode, panics if `fn_table` is null or if the read pointer is
    /// null (indicates a non-conforming server or a corrupted table).
    fn from_table(fn_table: usize) -> Self::Output;
}

impl_export!(Align16);
impl_export!(Align32);
impl_export!(Allot);
impl_export!(Callback);
impl_export!(Cleanup);
impl_export!(Clone);
impl_export!(Exec);
impl_export!(FindNative);
impl_export!(FindPublic);
impl_export!(FindPubVar);
impl_export!(FindTagId);
impl_export!(Flags);
impl_export!(GetAddr);
impl_export!(GetNative);
impl_export!(GetPublic);
impl_export!(GetPubVar);
impl_export!(GetString);
impl_export!(GetTag);
impl_export!(GetUserData);
impl_export!(Init);
impl_export!(InitJIT);
impl_export!(MemInfo);
impl_export!(NameLength);
impl_export!(NativeInfo);
impl_export!(NumNatives);
impl_export!(NumPublics);
impl_export!(NumPubVars);
impl_export!(NumTags);
impl_export!(Push);
impl_export!(PushArray);
impl_export!(PushString);
impl_export!(RaiseError);
impl_export!(Register);
impl_export!(Release);
impl_export!(SetCallback);
impl_export!(SetDebugHook);
impl_export!(SetString);
impl_export!(SetUserData);
impl_export!(StrLen);
impl_export!(UTF8Check);
impl_export!(UTF8Get);
impl_export!(UTF8Len);
impl_export!(UTF8Put);

// Open Multiplayer only — see the note on [`Exports`].
impl_export!(PushStringLen);
impl_export!(SetStringLen);
impl_export!(Swap16);
impl_export!(Swap32);
impl_export!(Swap64);
impl_export!(GetNativeByIndex);
impl_export!(MakeAddr);
impl_export!(StrSize);

/// Indices of the `amx_*` functions in the server's `amx_Exports` table.
///
/// The order is fixed by the SA-MP ABI — do not reorder.
///
/// Entries `[0..=43]` exist on both servers. Entries `[44..=51]` exist **only**
/// in the 52-slot table open.mp's Pawn component returns from
/// `getAmxFunctions()`; the SA-MP table ends at `[43]`, so resolving one of
/// them against a SA-MP table reads past its end. The `samp` crate exposes
/// them through `AmxOmpExt`, which checks the running mode first.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Exports {
    Align16 = 0,
    Align32 = 1,
    Align64 = 2,
    Allot = 3,
    Callback = 4,
    Cleanup = 5,
    Clone = 6,
    Exec = 7,
    FindNative = 8,
    FindPublic = 9,
    FindPubVar = 10,
    FindTagId = 11,
    Flags = 12,
    GetAddr = 13,
    GetNative = 14,
    GetPublic = 15,
    GetPubVar = 16,
    GetString = 17,
    GetTag = 18,
    GetUserData = 19,
    Init = 20,
    InitJIT = 21,
    MemInfo = 22,
    NameLength = 23,
    NativeInfo = 24,
    NumNatives = 25,
    NumPublics = 26,
    NumPubVars = 27,
    NumTags = 28,
    Push = 29,
    PushArray = 30,
    PushString = 31,
    RaiseError = 32,
    Register = 33,
    Release = 34,
    SetCallback = 35,
    SetDebugHook = 36,
    SetString = 37,
    SetUserData = 38,
    StrLen = 39,
    UTF8Check = 40,
    UTF8Get = 41,
    UTF8Len = 42,
    UTF8Put = 43,
    // --- Open Multiplayer only ---
    PushStringLen = 44,
    SetStringLen = 45,
    Swap16 = 46,
    Swap32 = 47,
    Swap64 = 48,
    GetNativeByIndex = 49,
    MakeAddr = 50,
    StrSize = 51,
}

impl From<Exports> for isize {
    fn from(exports: Exports) -> isize {
        exports as isize
    }
}
