#!/usr/bin/env python3
"""Generate set/get round trips for the generated open.mp wrappers.

A wrapper can be wrong in ways no unit test sees: the right name on the wrong
slot, a `float` read as an `int`, a stack the callee cleans by the wrong
amount. A running server sees all of them. For every generated setter with one
argument whose getter returns the same type, this writes a check that sets a
value different from the current one, reads it back, and restores the
original:

    set_x(v) then x() == v    both slots and both types are right
    x() still the old value   the setter ignored it — a rule of the server, or
                              a wrong slot; worth a look, not proof of either
    anything else             a wrong slot or type
    a crash on Windows        a wrong argument size: under `thiscall` the
                              callee pops the arguments

    scripts/omp-roundtrip.py          # writes examples/omp-showcase/src/round_trips.rs
    scripts/omp-roundtrip.py --check  # fails if that file is stale

It reads what `omp-wrappers.py` wrote, so run that first.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
GENERATED = REPO / "samp-sdk/src/omp/generated"
OUT = REPO / "examples/omp-showcase/src/round_trips.rs"

# Types a round trip can compare exactly, and that have an obvious "other value".
COMPARABLE = {"i32", "u32", "i16", "u16", "i8", "u8", "i64", "u64", "f32", "bool"}

ENTRY = re.compile(
    r"pub fn (\w+)\(\s*(\w+): (\w+)((?:,\s*\w+: [^,)]+)*),?\s*\)\s*(?:->\s*([^=]+?))?\s*=",
    re.S,
)


def wrappers() -> dict[str, dict]:
    """name -> {handle, this, params, ret} for every `virtual_fns!` entry."""
    found = {}
    for path in sorted(GENERATED.glob("*.rs")):
        for m in ENTRY.finditer(path.read_text()):
            name, this, handle, rest, ret = m.groups()
            params = [p.split(":")[1].strip() for p in rest.split(",") if ":" in p]
            found[name] = {"handle": handle, "this": this, "params": params,
                           "ret": ret.strip() if ret else None}
    return found


def pairs(found: dict) -> dict[str, list[tuple[str, str, str]]]:
    """handle -> [(getter, setter, type)] where the two agree."""
    out: dict[str, list] = {}
    for setter, w in found.items():
        m = re.match(r"(\w+?)_set_(\w+)$", setter)
        if not m or len(w["params"]) != 1 or w["params"][0] not in COMPARABLE:
            continue
        getter = f"{m.group(1)}_{m.group(2)}"
        g = found.get(getter)
        if g and g["handle"] == w["handle"] and not g["params"] and g["ret"] == w["params"][0]:
            out.setdefault(w["handle"], []).append((getter, setter, w["params"][0]))
    return out


def render(by_handle: dict) -> str:
    lines = [
        "//! Set/get round trips over the generated wrappers — generated by",
        "//! `scripts/omp-roundtrip.py`. Do not edit.",
        "",
        "use samp::omp::*;",
        "",
        "use crate::report::{Other, Report};",
        "",
    ]
    for handle in sorted(by_handle):
        fn = "round_trips_" + re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", handle[1:]).lower()
        lines += [
            f"/// Every setter of `{handle}` that has a matching getter.",
            "///",
            "/// # Safety",
            f"/// `handle` must be a live `{handle}`.",
            f"pub unsafe fn {fn}(handle: *mut {handle}, report: &mut Report) {{",
        ]
        for getter, setter, ty in sorted(by_handle[handle]):
            lines += [
                f'    report.begin("{getter}");',
                "    unsafe {",
                f"        let before: {ty} = {getter}(handle);",
                "        let want = before.other();",
                f"        {setter}(handle, want);",
                f'        report.round_trip("{getter}", before, want, {getter}(handle));',
                f"        {setter}(handle, before);",
                "    }",
            ]
        lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    by_handle = pairs(wrappers())
    text = render(by_handle)
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(REPO)} is stale")
            return 1
        print("round trips are current")
        return 0
    OUT.write_text(text)
    total = sum(len(v) for v in by_handle.values())
    print(f"wrote {OUT.relative_to(REPO)}: {total} round trips over {len(by_handle)} handles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
