//! Proc macros for the `rust-samp` toolkit.
//!
//! - `#[native]` — generates the `extern "C"` FFI wrapper for a Rust function,
//!   parsing arguments via [`AmxCell`] and handling the return value.
//! - `initialize_plugin!` — generates the entry points required by the server
//!   (`Supports`/`Load`/`Unload`/`AmxLoad`/`AmxUnload`/`ProcessTick` on SA-MP
//!   and `ComponentEntryPoint` + vtable on Open Multiplayer), as well as native registration.
//! - `#[derive(SampPlugin)]` — shortcut for an empty `impl SampPlugin for T {}`.
//!
//! This crate only compiles when loaded by `samp` via reexport — it has no
//! runtime API of its own.
//!
//! [`AmxCell`]: samp::cell::AmxCell

#![recursion_limit = "128"]

use proc_macro::TokenStream;

mod native;
mod plugin;

/// Prefix applied to the name of the `extern "C"` wrapper function generated by `#[native]`.
/// Avoids collision with any function name declared by the developer.
pub(crate) const NATIVE_PREFIX: &str = "__samp_native_";

/// Prefix applied to the name of the native registration block in `initialize_plugin!`.
pub(crate) const REG_PREFIX: &str = "__samp_reg_";

/// Generates the `extern "C"` wrapper that reads the AMX argument table, parses
/// it into the Rust types declared in the signature and invokes the marked method.
#[proc_macro_attribute]
pub fn native(args: TokenStream, input: TokenStream) -> TokenStream {
    native::create_native(args, input)
}

/// Generates the entry points required by the server (SA-MP + Open Multiplayer), the Rust
/// `IComponent` vtable and the registration of the plugin's native list.
#[proc_macro]
pub fn initialize_plugin(input: TokenStream) -> TokenStream {
    plugin::create_plugin(input)
}

/// Generates `impl SampPlugin for T {}` with all methods using the default behavior
/// (empty). Use for structs that do not need to customize any lifecycle callback —
/// write the `impl SampPlugin` manually when some method needs custom logic.
///
/// ```rust,ignore
/// use samp::prelude::*;
///
/// #[derive(SampPlugin)]
/// struct SimplePlugin { counter: u32 }
///
/// // With logic in on_load → do not use the derive
/// struct AdvancedPlugin;
/// impl SampPlugin for AdvancedPlugin {
///     fn on_load(&mut self) { println!("plugin loaded"); }
/// }
/// ```
#[proc_macro_derive(SampPlugin)]
pub fn derive_samp_plugin(input: TokenStream) -> TokenStream {
    plugin::derive_samp_plugin(input)
}
